// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getV1AuthSearchToken, postV1Company, postV1Position, getV1Submissions, patchV1Submissions, postV1Submissions, getV1SubmissionsMe, getV1AutocompleteCompany, getV1AutocompletePosition, getV1AutocompleteLocation } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { GetV1AuthSearchTokenData, PostV1CompanyData, PostV1CompanyError, PostV1CompanyResponse, PostV1PositionData, PostV1PositionError, PostV1PositionResponse, GetV1SubmissionsData, PatchV1SubmissionsData, PatchV1SubmissionsError, PatchV1SubmissionsResponse, PostV1SubmissionsData, PostV1SubmissionsError, PostV1SubmissionsResponse, GetV1SubmissionsMeData, GetV1AutocompleteCompanyData, GetV1AutocompletePositionData, GetV1AutocompleteLocationData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getV1AuthSearchTokenQueryKey = (options?: Options<GetV1AuthSearchTokenData>) => createQueryKey('getV1AuthSearchToken', options);

/**
 * Get a tenant token for searching, filtering, and sorting (expires in 1 day)
 */
export const getV1AuthSearchTokenOptions = (options?: Options<GetV1AuthSearchTokenData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1AuthSearchToken({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1AuthSearchTokenQueryKey(options)
    });
};

export const postV1CompanyQueryKey = (options?: Options<PostV1CompanyData>) => createQueryKey('postV1Company', options);

/**
 * Create a new company
 */
export const postV1CompanyOptions = (options?: Options<PostV1CompanyData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postV1Company({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postV1CompanyQueryKey(options)
    });
};

/**
 * Create a new company
 */
export const postV1CompanyMutation = (options?: Partial<Options<PostV1CompanyData>>): UseMutationOptions<PostV1CompanyResponse, PostV1CompanyError, Options<PostV1CompanyData>> => {
    const mutationOptions: UseMutationOptions<PostV1CompanyResponse, PostV1CompanyError, Options<PostV1CompanyData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postV1Company({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1PositionQueryKey = (options?: Options<PostV1PositionData>) => createQueryKey('postV1Position', options);

/**
 * Create a new position for an existing company using company name
 */
export const postV1PositionOptions = (options?: Options<PostV1PositionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postV1Position({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postV1PositionQueryKey(options)
    });
};

/**
 * Create a new position for an existing company using company name
 */
export const postV1PositionMutation = (options?: Partial<Options<PostV1PositionData>>): UseMutationOptions<PostV1PositionResponse, PostV1PositionError, Options<PostV1PositionData>> => {
    const mutationOptions: UseMutationOptions<PostV1PositionResponse, PostV1PositionError, Options<PostV1PositionData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postV1Position({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1SubmissionsQueryKey = (options: Options<GetV1SubmissionsData>) => createQueryKey('getV1Submissions', options);

/**
 * Retrieve co-op submission records with pagination and filtering
 */
export const getV1SubmissionsOptions = (options: Options<GetV1SubmissionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1Submissions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1SubmissionsQueryKey(options)
    });
};

/**
 * Update an existing co-op submission
 */
export const patchV1SubmissionsMutation = (options?: Partial<Options<PatchV1SubmissionsData>>): UseMutationOptions<PatchV1SubmissionsResponse, PatchV1SubmissionsError, Options<PatchV1SubmissionsData>> => {
    const mutationOptions: UseMutationOptions<PatchV1SubmissionsResponse, PatchV1SubmissionsError, Options<PatchV1SubmissionsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await patchV1Submissions({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1SubmissionsQueryKey = (options?: Options<PostV1SubmissionsData>) => createQueryKey('postV1Submissions', options);

/**
 * Create new co-op submission(s)
 */
export const postV1SubmissionsOptions = (options?: Options<PostV1SubmissionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postV1Submissions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postV1SubmissionsQueryKey(options)
    });
};

/**
 * Create new co-op submission(s)
 */
export const postV1SubmissionsMutation = (options?: Partial<Options<PostV1SubmissionsData>>): UseMutationOptions<PostV1SubmissionsResponse, PostV1SubmissionsError, Options<PostV1SubmissionsData>> => {
    const mutationOptions: UseMutationOptions<PostV1SubmissionsResponse, PostV1SubmissionsError, Options<PostV1SubmissionsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postV1Submissions({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getV1SubmissionsMeQueryKey = (options?: Options<GetV1SubmissionsMeData>) => createQueryKey('getV1SubmissionsMe', options);

/**
 * Retrieve all co-op submissions owned by the authenticated user
 */
export const getV1SubmissionsMeOptions = (options?: Options<GetV1SubmissionsMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1SubmissionsMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1SubmissionsMeQueryKey(options)
    });
};

export const getV1AutocompleteCompanyQueryKey = (options: Options<GetV1AutocompleteCompanyData>) => createQueryKey('getV1AutocompleteCompany', options);

/**
 * Search for companies by name with fuzzy matching
 */
export const getV1AutocompleteCompanyOptions = (options: Options<GetV1AutocompleteCompanyData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1AutocompleteCompany({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1AutocompleteCompanyQueryKey(options)
    });
};

export const getV1AutocompletePositionQueryKey = (options: Options<GetV1AutocompletePositionData>) => createQueryKey('getV1AutocompletePosition', options);

/**
 * Search for positions within a specific company
 */
export const getV1AutocompletePositionOptions = (options: Options<GetV1AutocompletePositionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1AutocompletePosition({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1AutocompletePositionQueryKey(options)
    });
};

export const getV1AutocompleteLocationQueryKey = (options: Options<GetV1AutocompleteLocationData>) => createQueryKey('getV1AutocompleteLocation', options);

/**
 * Search for locations with fuzzy matching across city, state, and state code
 */
export const getV1AutocompleteLocationOptions = (options: Options<GetV1AutocompleteLocationData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getV1AutocompleteLocation({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getV1AutocompleteLocationQueryKey(options)
    });
};