services:

  database:
    ports:
      - "5432:5432"

  meilisearch:
    networks:
      - app_network 
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development

  prestart:
    build: 
      context: ./back
      dockerfile: Dockerfile
      target: seeding-stage
      platforms:
        - linux/amd64
    command:
      - deno
      - task
      - prestart
    environment:
      - DOMAIN=https://localhost
    profiles:
      - seed

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
      target: development-stage
      platforms:
        - linux/amd64
    ports:
      - "3000:3000"
    command:
      - deno
      - run
      - watch
    develop:
      watch: 
        - path: ./back/
          action: sync
          target: /app/
          ignore:
            - node_modules/
    environment:
      - DOMAIN=https://localhost

  reverse-proxy:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development-stage
    develop:
      watch: 
        - path: ./front/
          action: sync
          target: /app/
          ignore:
            - node_modules/
    environment:
      - VITE_API_URL=http://backend:3000
      - VITE_SEARCH_API_URL=http://meilisearch:7700
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 80
