services:
  database:
    ports:
      - "5432:5432"
    env_file:
      - .dev.env

  meilisearch:
    ports:
      - "7700:7700"
    env_file:
      - .dev.env
    environment:
      - MEILI_HOST=${MEILI_HOST?Variable not set}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY?Variable not set}
      - MEILI_ENV=${MEILI_ENV?Variable not set}

  # prestart:
  #   command:
  #     - deno
  #     - task
  #     - prestart
  #   env_file:
  #     - .dev.env
  #   environment:
  #     - MEILI_HOST=meilisearch:7700
  #     - MEILI_MASTER_KEY=${MEILI_MASTER_KEY?Variable not set}
  #     - POSTGRES_SERVER=database

  backend:
    ports:
      - "3000:3000"
    command:
      - "./openmario"
    develop:
      watch: 
        - path: ./back/
          action: sync
          target: /app/
          ignore:
            - node_modules/
    env_file:
      - .dev.env


  frontend:
    build:
      target: development-stage
      args:
          - NODE_ENV=development
    develop:
      watch: 
        - path: ./front/
          action: sync
          target: /app/
          ignore:
            - node_modules/
    env_file:
      - .dev.env
    environment:
        - VITE_API_URL=http://localhost
    command: npm run dev -- --host 0.0.0.0 --port 80
