/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ProfessorsRouteImport } from './routes/professors'
import { Route as EsapRouteImport } from './routes/esap'
import { Route as SearchRouteImport } from './routes/_search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'
import { Route as EsapIndexRouteImport } from './routes/esap/index'
import { Route as SalaryDialogRouteImport } from './routes/salary/_dialog'
import { Route as ProfessorsProfessor_idRouteImport } from './routes/professors/$professor_id'
import { Route as SearchCoursesRouteImport } from './routes/_search/courses'
import { Route as EsapCompany_idIndexRouteImport } from './routes/esap/$company_id/index'
import { Route as SalaryDialogSubmissionsRouteImport } from './routes/salary/_dialog/submissions'
import { Route as SalaryDialogDraftsRouteImport } from './routes/salary/_dialog/drafts'
import { Route as SalaryDialogAutoFillRouteImport } from './routes/salary/_dialog/auto-fill'
import { Route as SalaryDialogFormRouteImport } from './routes/salary/_dialog/_form'
import { Route as EsapCompany_idReviewsRouteImport } from './routes/esap/$company_id/reviews'
import { Route as EsapCompany_idPositionsRouteImport } from './routes/esap/$company_id/positions'
import { Route as EsapCompany_idPosition_idRouteImport } from './routes/esap/$company_id/$position_id'
import { Route as SearchCoursesProfileRouteImport } from './routes/_search/courses.profile'
import { Route as SearchCoursesPlanRouteImport } from './routes/_search/courses.plan'
import { Route as SearchCoursesExploreRouteImport } from './routes/_search/courses.explore'
import { Route as SalaryDialogFormReportRouteImport } from './routes/salary/_dialog/_form/report'
import { Route as SearchCoursesProfileCourse_idRouteImport } from './routes/_search/courses.profile.$course_id'
import { Route as SearchCoursesPlanCourse_idRouteImport } from './routes/_search/courses.plan.$course_id'
import { Route as SearchCoursesExploreCourse_idRouteImport } from './routes/_search/courses.explore.$course_id'
import { Route as SalaryDialogFormReportedKeyRouteImport } from './routes/salary/_dialog/_form/reported.$key'
import { Route as SalaryDialogFormReportChar123IdxChar125RouteImport } from './routes/salary/_dialog/_form/report.{-$idx}'

const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsRoute = ProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => rootRouteImport,
} as any)
const EsapRoute = EsapRouteImport.update({
  id: '/esap',
  path: '/esap',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorsRoute,
} as any)
const EsapIndexRoute = EsapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsapRoute,
} as any)
const SalaryDialogRoute = SalaryDialogRouteImport.update({
  id: '/_dialog',
  getParentRoute: () => SalaryRoute,
} as any)
const ProfessorsProfessor_idRoute = ProfessorsProfessor_idRouteImport.update({
  id: '/$professor_id',
  path: '/$professor_id',
  getParentRoute: () => ProfessorsRoute,
} as any)
const SearchCoursesRoute = SearchCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SearchRoute,
} as any)
const EsapCompany_idIndexRoute = EsapCompany_idIndexRouteImport.update({
  id: '/$company_id/',
  path: '/$company_id/',
  getParentRoute: () => EsapRoute,
} as any)
const SalaryDialogSubmissionsRoute = SalaryDialogSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogDraftsRoute = SalaryDialogDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogAutoFillRoute = SalaryDialogAutoFillRouteImport.update({
  id: '/auto-fill',
  path: '/auto-fill',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogFormRoute = SalaryDialogFormRouteImport.update({
  id: '/_form',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const EsapCompany_idReviewsRoute = EsapCompany_idReviewsRouteImport.update({
  id: '/$company_id/reviews',
  path: '/$company_id/reviews',
  getParentRoute: () => EsapRoute,
} as any)
const EsapCompany_idPositionsRoute = EsapCompany_idPositionsRouteImport.update({
  id: '/$company_id/positions',
  path: '/$company_id/positions',
  getParentRoute: () => EsapRoute,
} as any)
const EsapCompany_idPosition_idRoute =
  EsapCompany_idPosition_idRouteImport.update({
    id: '/$company_id/$position_id',
    path: '/$company_id/$position_id',
    getParentRoute: () => EsapRoute,
  } as any)
const SearchCoursesProfileRoute = SearchCoursesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SearchCoursesRoute,
} as any)
const SearchCoursesPlanRoute = SearchCoursesPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SearchCoursesRoute,
} as any)
const SearchCoursesExploreRoute = SearchCoursesExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => SearchCoursesRoute,
} as any)
const SalaryDialogFormReportRoute = SalaryDialogFormReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SalaryDialogFormRoute,
} as any)
const SearchCoursesProfileCourse_idRoute =
  SearchCoursesProfileCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => SearchCoursesProfileRoute,
  } as any)
const SearchCoursesPlanCourse_idRoute =
  SearchCoursesPlanCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => SearchCoursesPlanRoute,
  } as any)
const SearchCoursesExploreCourse_idRoute =
  SearchCoursesExploreCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => SearchCoursesExploreRoute,
  } as any)
const SalaryDialogFormReportedKeyRoute =
  SalaryDialogFormReportedKeyRouteImport.update({
    id: '/reported/$key',
    path: '/reported/$key',
    getParentRoute: () => SalaryDialogFormRoute,
  } as any)
const SalaryDialogFormReportChar123IdxChar125Route =
  SalaryDialogFormReportChar123IdxChar125RouteImport.update({
    id: '/{-$idx}',
    path: '/{-$idx}',
    getParentRoute: () => SalaryDialogFormReportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esap': typeof EsapRouteWithChildren
  '/professors': typeof ProfessorsRouteWithChildren
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/courses': typeof SearchCoursesRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/esap/': typeof EsapIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/courses/profile': typeof SearchCoursesProfileRouteWithChildren
  '/esap/$company_id/$position_id': typeof EsapCompany_idPosition_idRoute
  '/esap/$company_id/positions': typeof EsapCompany_idPositionsRoute
  '/esap/$company_id/reviews': typeof EsapCompany_idReviewsRoute
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/esap/$company_id/': typeof EsapCompany_idIndexRoute
  '/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/courses/profile/$course_id': typeof SearchCoursesProfileCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/courses': typeof SearchCoursesRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/esap': typeof EsapIndexRoute
  '/professors': typeof ProfessorsIndexRoute
  '/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/courses/profile': typeof SearchCoursesProfileRouteWithChildren
  '/esap/$company_id/$position_id': typeof EsapCompany_idPosition_idRoute
  '/esap/$company_id/positions': typeof EsapCompany_idPositionsRoute
  '/esap/$company_id/reviews': typeof EsapCompany_idReviewsRoute
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/esap/$company_id': typeof EsapCompany_idIndexRoute
  '/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/courses/profile/$course_id': typeof SearchCoursesProfileCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_search': typeof SearchRouteWithChildren
  '/esap': typeof EsapRouteWithChildren
  '/professors': typeof ProfessorsRouteWithChildren
  '/salary': typeof SalaryRouteWithChildren
  '/_search/courses': typeof SearchCoursesRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/salary/_dialog': typeof SalaryDialogRouteWithChildren
  '/esap/': typeof EsapIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/_search/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/_search/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/_search/courses/profile': typeof SearchCoursesProfileRouteWithChildren
  '/esap/$company_id/$position_id': typeof EsapCompany_idPosition_idRoute
  '/esap/$company_id/positions': typeof EsapCompany_idPositionsRoute
  '/esap/$company_id/reviews': typeof EsapCompany_idReviewsRoute
  '/salary/_dialog/_form': typeof SalaryDialogFormRouteWithChildren
  '/salary/_dialog/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/_dialog/drafts': typeof SalaryDialogDraftsRoute
  '/salary/_dialog/submissions': typeof SalaryDialogSubmissionsRoute
  '/esap/$company_id/': typeof EsapCompany_idIndexRoute
  '/_search/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/_search/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/_search/courses/profile/$course_id': typeof SearchCoursesProfileCourse_idRoute
  '/salary/_dialog/_form/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/_dialog/_form/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/_dialog/_form/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esap'
    | '/professors'
    | '/salary'
    | '/courses'
    | '/professors/$professor_id'
    | '/esap/'
    | '/professors/'
    | '/courses/explore'
    | '/courses/plan'
    | '/courses/profile'
    | '/esap/$company_id/$position_id'
    | '/esap/$company_id/positions'
    | '/esap/$company_id/reviews'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/esap/$company_id/'
    | '/courses/explore/$course_id'
    | '/courses/plan/$course_id'
    | '/courses/profile/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/salary'
    | '/courses'
    | '/professors/$professor_id'
    | '/esap'
    | '/professors'
    | '/courses/explore'
    | '/courses/plan'
    | '/courses/profile'
    | '/esap/$company_id/$position_id'
    | '/esap/$company_id/positions'
    | '/esap/$company_id/reviews'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/esap/$company_id'
    | '/courses/explore/$course_id'
    | '/courses/plan/$course_id'
    | '/courses/profile/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  id:
    | '__root__'
    | '/'
    | '/_search'
    | '/esap'
    | '/professors'
    | '/salary'
    | '/_search/courses'
    | '/professors/$professor_id'
    | '/salary/_dialog'
    | '/esap/'
    | '/professors/'
    | '/_search/courses/explore'
    | '/_search/courses/plan'
    | '/_search/courses/profile'
    | '/esap/$company_id/$position_id'
    | '/esap/$company_id/positions'
    | '/esap/$company_id/reviews'
    | '/salary/_dialog/_form'
    | '/salary/_dialog/auto-fill'
    | '/salary/_dialog/drafts'
    | '/salary/_dialog/submissions'
    | '/esap/$company_id/'
    | '/_search/courses/explore/$course_id'
    | '/_search/courses/plan/$course_id'
    | '/_search/courses/profile/$course_id'
    | '/salary/_dialog/_form/report'
    | '/salary/_dialog/_form/report/{-$idx}'
    | '/salary/_dialog/_form/reported/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRouteWithChildren
  EsapRoute: typeof EsapRouteWithChildren
  ProfessorsRoute: typeof ProfessorsRouteWithChildren
  SalaryRoute: typeof SalaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors': {
      id: '/professors'
      path: '/professors'
      fullPath: '/professors'
      preLoaderRoute: typeof ProfessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esap': {
      id: '/esap'
      path: '/esap'
      fullPath: '/esap'
      preLoaderRoute: typeof EsapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_search': {
      id: '/_search'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof ProfessorsRoute
    }
    '/esap/': {
      id: '/esap/'
      path: '/'
      fullPath: '/esap/'
      preLoaderRoute: typeof EsapIndexRouteImport
      parentRoute: typeof EsapRoute
    }
    '/salary/_dialog': {
      id: '/salary/_dialog'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogRouteImport
      parentRoute: typeof SalaryRoute
    }
    '/professors/$professor_id': {
      id: '/professors/$professor_id'
      path: '/$professor_id'
      fullPath: '/professors/$professor_id'
      preLoaderRoute: typeof ProfessorsProfessor_idRouteImport
      parentRoute: typeof ProfessorsRoute
    }
    '/_search/courses': {
      id: '/_search/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof SearchCoursesRouteImport
      parentRoute: typeof SearchRoute
    }
    '/esap/$company_id/': {
      id: '/esap/$company_id/'
      path: '/$company_id'
      fullPath: '/esap/$company_id/'
      preLoaderRoute: typeof EsapCompany_idIndexRouteImport
      parentRoute: typeof EsapRoute
    }
    '/salary/_dialog/submissions': {
      id: '/salary/_dialog/submissions'
      path: '/submissions'
      fullPath: '/salary/submissions'
      preLoaderRoute: typeof SalaryDialogSubmissionsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/drafts': {
      id: '/salary/_dialog/drafts'
      path: '/drafts'
      fullPath: '/salary/drafts'
      preLoaderRoute: typeof SalaryDialogDraftsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/auto-fill': {
      id: '/salary/_dialog/auto-fill'
      path: '/auto-fill'
      fullPath: '/salary/auto-fill'
      preLoaderRoute: typeof SalaryDialogAutoFillRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/_form': {
      id: '/salary/_dialog/_form'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogFormRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/esap/$company_id/reviews': {
      id: '/esap/$company_id/reviews'
      path: '/$company_id/reviews'
      fullPath: '/esap/$company_id/reviews'
      preLoaderRoute: typeof EsapCompany_idReviewsRouteImport
      parentRoute: typeof EsapRoute
    }
    '/esap/$company_id/positions': {
      id: '/esap/$company_id/positions'
      path: '/$company_id/positions'
      fullPath: '/esap/$company_id/positions'
      preLoaderRoute: typeof EsapCompany_idPositionsRouteImport
      parentRoute: typeof EsapRoute
    }
    '/esap/$company_id/$position_id': {
      id: '/esap/$company_id/$position_id'
      path: '/$company_id/$position_id'
      fullPath: '/esap/$company_id/$position_id'
      preLoaderRoute: typeof EsapCompany_idPosition_idRouteImport
      parentRoute: typeof EsapRoute
    }
    '/_search/courses/profile': {
      id: '/_search/courses/profile'
      path: '/profile'
      fullPath: '/courses/profile'
      preLoaderRoute: typeof SearchCoursesProfileRouteImport
      parentRoute: typeof SearchCoursesRoute
    }
    '/_search/courses/plan': {
      id: '/_search/courses/plan'
      path: '/plan'
      fullPath: '/courses/plan'
      preLoaderRoute: typeof SearchCoursesPlanRouteImport
      parentRoute: typeof SearchCoursesRoute
    }
    '/_search/courses/explore': {
      id: '/_search/courses/explore'
      path: '/explore'
      fullPath: '/courses/explore'
      preLoaderRoute: typeof SearchCoursesExploreRouteImport
      parentRoute: typeof SearchCoursesRoute
    }
    '/salary/_dialog/_form/report': {
      id: '/salary/_dialog/_form/report'
      path: '/report'
      fullPath: '/salary/report'
      preLoaderRoute: typeof SalaryDialogFormReportRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/_search/courses/profile/$course_id': {
      id: '/_search/courses/profile/$course_id'
      path: '/$course_id'
      fullPath: '/courses/profile/$course_id'
      preLoaderRoute: typeof SearchCoursesProfileCourse_idRouteImport
      parentRoute: typeof SearchCoursesProfileRoute
    }
    '/_search/courses/plan/$course_id': {
      id: '/_search/courses/plan/$course_id'
      path: '/$course_id'
      fullPath: '/courses/plan/$course_id'
      preLoaderRoute: typeof SearchCoursesPlanCourse_idRouteImport
      parentRoute: typeof SearchCoursesPlanRoute
    }
    '/_search/courses/explore/$course_id': {
      id: '/_search/courses/explore/$course_id'
      path: '/$course_id'
      fullPath: '/courses/explore/$course_id'
      preLoaderRoute: typeof SearchCoursesExploreCourse_idRouteImport
      parentRoute: typeof SearchCoursesExploreRoute
    }
    '/salary/_dialog/_form/reported/$key': {
      id: '/salary/_dialog/_form/reported/$key'
      path: '/reported/$key'
      fullPath: '/salary/reported/$key'
      preLoaderRoute: typeof SalaryDialogFormReportedKeyRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/salary/_dialog/_form/report/{-$idx}': {
      id: '/salary/_dialog/_form/report/{-$idx}'
      path: '/{-$idx}'
      fullPath: '/salary/report/{-$idx}'
      preLoaderRoute: typeof SalaryDialogFormReportChar123IdxChar125RouteImport
      parentRoute: typeof SalaryDialogFormReportRoute
    }
  }
}

interface SearchCoursesExploreRouteChildren {
  SearchCoursesExploreCourse_idRoute: typeof SearchCoursesExploreCourse_idRoute
}

const SearchCoursesExploreRouteChildren: SearchCoursesExploreRouteChildren = {
  SearchCoursesExploreCourse_idRoute: SearchCoursesExploreCourse_idRoute,
}

const SearchCoursesExploreRouteWithChildren =
  SearchCoursesExploreRoute._addFileChildren(SearchCoursesExploreRouteChildren)

interface SearchCoursesPlanRouteChildren {
  SearchCoursesPlanCourse_idRoute: typeof SearchCoursesPlanCourse_idRoute
}

const SearchCoursesPlanRouteChildren: SearchCoursesPlanRouteChildren = {
  SearchCoursesPlanCourse_idRoute: SearchCoursesPlanCourse_idRoute,
}

const SearchCoursesPlanRouteWithChildren =
  SearchCoursesPlanRoute._addFileChildren(SearchCoursesPlanRouteChildren)

interface SearchCoursesProfileRouteChildren {
  SearchCoursesProfileCourse_idRoute: typeof SearchCoursesProfileCourse_idRoute
}

const SearchCoursesProfileRouteChildren: SearchCoursesProfileRouteChildren = {
  SearchCoursesProfileCourse_idRoute: SearchCoursesProfileCourse_idRoute,
}

const SearchCoursesProfileRouteWithChildren =
  SearchCoursesProfileRoute._addFileChildren(SearchCoursesProfileRouteChildren)

interface SearchCoursesRouteChildren {
  SearchCoursesExploreRoute: typeof SearchCoursesExploreRouteWithChildren
  SearchCoursesPlanRoute: typeof SearchCoursesPlanRouteWithChildren
  SearchCoursesProfileRoute: typeof SearchCoursesProfileRouteWithChildren
}

const SearchCoursesRouteChildren: SearchCoursesRouteChildren = {
  SearchCoursesExploreRoute: SearchCoursesExploreRouteWithChildren,
  SearchCoursesPlanRoute: SearchCoursesPlanRouteWithChildren,
  SearchCoursesProfileRoute: SearchCoursesProfileRouteWithChildren,
}

const SearchCoursesRouteWithChildren = SearchCoursesRoute._addFileChildren(
  SearchCoursesRouteChildren,
)

interface SearchRouteChildren {
  SearchCoursesRoute: typeof SearchCoursesRouteWithChildren
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchCoursesRoute: SearchCoursesRouteWithChildren,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface EsapRouteChildren {
  EsapIndexRoute: typeof EsapIndexRoute
  EsapCompany_idPosition_idRoute: typeof EsapCompany_idPosition_idRoute
  EsapCompany_idPositionsRoute: typeof EsapCompany_idPositionsRoute
  EsapCompany_idReviewsRoute: typeof EsapCompany_idReviewsRoute
  EsapCompany_idIndexRoute: typeof EsapCompany_idIndexRoute
}

const EsapRouteChildren: EsapRouteChildren = {
  EsapIndexRoute: EsapIndexRoute,
  EsapCompany_idPosition_idRoute: EsapCompany_idPosition_idRoute,
  EsapCompany_idPositionsRoute: EsapCompany_idPositionsRoute,
  EsapCompany_idReviewsRoute: EsapCompany_idReviewsRoute,
  EsapCompany_idIndexRoute: EsapCompany_idIndexRoute,
}

const EsapRouteWithChildren = EsapRoute._addFileChildren(EsapRouteChildren)

interface ProfessorsRouteChildren {
  ProfessorsProfessor_idRoute: typeof ProfessorsProfessor_idRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
}

const ProfessorsRouteChildren: ProfessorsRouteChildren = {
  ProfessorsProfessor_idRoute: ProfessorsProfessor_idRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
}

const ProfessorsRouteWithChildren = ProfessorsRoute._addFileChildren(
  ProfessorsRouteChildren,
)

interface SalaryDialogFormReportRouteChildren {
  SalaryDialogFormReportChar123IdxChar125Route: typeof SalaryDialogFormReportChar123IdxChar125Route
}

const SalaryDialogFormReportRouteChildren: SalaryDialogFormReportRouteChildren =
  {
    SalaryDialogFormReportChar123IdxChar125Route:
      SalaryDialogFormReportChar123IdxChar125Route,
  }

const SalaryDialogFormReportRouteWithChildren =
  SalaryDialogFormReportRoute._addFileChildren(
    SalaryDialogFormReportRouteChildren,
  )

interface SalaryDialogFormRouteChildren {
  SalaryDialogFormReportRoute: typeof SalaryDialogFormReportRouteWithChildren
  SalaryDialogFormReportedKeyRoute: typeof SalaryDialogFormReportedKeyRoute
}

const SalaryDialogFormRouteChildren: SalaryDialogFormRouteChildren = {
  SalaryDialogFormReportRoute: SalaryDialogFormReportRouteWithChildren,
  SalaryDialogFormReportedKeyRoute: SalaryDialogFormReportedKeyRoute,
}

const SalaryDialogFormRouteWithChildren =
  SalaryDialogFormRoute._addFileChildren(SalaryDialogFormRouteChildren)

interface SalaryDialogRouteChildren {
  SalaryDialogFormRoute: typeof SalaryDialogFormRouteWithChildren
  SalaryDialogAutoFillRoute: typeof SalaryDialogAutoFillRoute
  SalaryDialogDraftsRoute: typeof SalaryDialogDraftsRoute
  SalaryDialogSubmissionsRoute: typeof SalaryDialogSubmissionsRoute
}

const SalaryDialogRouteChildren: SalaryDialogRouteChildren = {
  SalaryDialogFormRoute: SalaryDialogFormRouteWithChildren,
  SalaryDialogAutoFillRoute: SalaryDialogAutoFillRoute,
  SalaryDialogDraftsRoute: SalaryDialogDraftsRoute,
  SalaryDialogSubmissionsRoute: SalaryDialogSubmissionsRoute,
}

const SalaryDialogRouteWithChildren = SalaryDialogRoute._addFileChildren(
  SalaryDialogRouteChildren,
)

interface SalaryRouteChildren {
  SalaryDialogRoute: typeof SalaryDialogRouteWithChildren
}

const SalaryRouteChildren: SalaryRouteChildren = {
  SalaryDialogRoute: SalaryDialogRouteWithChildren,
}

const SalaryRouteWithChildren =
  SalaryRoute._addFileChildren(SalaryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRouteWithChildren,
  EsapRoute: EsapRouteWithChildren,
  ProfessorsRoute: ProfessorsRouteWithChildren,
  SalaryRoute: SalaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
