/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as SearchRouteImport } from './routes/_search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalaryDialogRouteImport } from './routes/salary/_dialog'
import { Route as SearchCoursesRouteImport } from './routes/_search/courses'
import { Route as SalaryDialogSubmissionsRouteImport } from './routes/salary/_dialog/submissions'
import { Route as SalaryDialogDraftsRouteImport } from './routes/salary/_dialog/drafts'
import { Route as SalaryDialogAutoFillRouteImport } from './routes/salary/_dialog/auto-fill'
import { Route as SalaryDialogFormRouteImport } from './routes/salary/_dialog/_form'
import { Route as SearchCoursesPlanRouteImport } from './routes/_search/courses.plan'
import { Route as SearchCoursesExploreRouteImport } from './routes/_search/courses.explore'
import { Route as SalaryDialogFormReportRouteImport } from './routes/salary/_dialog/_form/report'
import { Route as SearchCoursesPlanCourse_idRouteImport } from './routes/_search/courses.plan.$course_id'
import { Route as SearchCoursesExploreCourse_idRouteImport } from './routes/_search/courses.explore.$course_id'
import { Route as SalaryDialogFormReportedKeyRouteImport } from './routes/salary/_dialog/_form/reported.$key'
import { Route as SalaryDialogFormReportChar123IdxChar125RouteImport } from './routes/salary/_dialog/_form/report.{-$idx}'

const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryDialogRoute = SalaryDialogRouteImport.update({
  id: '/_dialog',
  getParentRoute: () => SalaryRoute,
} as any)
const SearchCoursesRoute = SearchCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SearchRoute,
} as any)
const SalaryDialogSubmissionsRoute = SalaryDialogSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogDraftsRoute = SalaryDialogDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogAutoFillRoute = SalaryDialogAutoFillRouteImport.update({
  id: '/auto-fill',
  path: '/auto-fill',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogFormRoute = SalaryDialogFormRouteImport.update({
  id: '/_form',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SearchCoursesPlanRoute = SearchCoursesPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SearchCoursesRoute,
} as any)
const SearchCoursesExploreRoute = SearchCoursesExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => SearchCoursesRoute,
} as any)
const SalaryDialogFormReportRoute = SalaryDialogFormReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SalaryDialogFormRoute,
} as any)
const SearchCoursesPlanCourse_idRoute =
  SearchCoursesPlanCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => SearchCoursesPlanRoute,
  } as any)
const SearchCoursesExploreCourse_idRoute =
  SearchCoursesExploreCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => SearchCoursesExploreRoute,
  } as any)
const SalaryDialogFormReportedKeyRoute =
  SalaryDialogFormReportedKeyRouteImport.update({
    id: '/reported/$key',
    path: '/reported/$key',
    getParentRoute: () => SalaryDialogFormRoute,
  } as any)
const SalaryDialogFormReportChar123IdxChar125Route =
  SalaryDialogFormReportChar123IdxChar125RouteImport.update({
    id: '/{-$idx}',
    path: '/{-$idx}',
    getParentRoute: () => SalaryDialogFormReportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/courses': typeof SearchCoursesRouteWithChildren
  '/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/courses': typeof SearchCoursesRouteWithChildren
  '/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_search': typeof SearchRouteWithChildren
  '/salary': typeof SalaryRouteWithChildren
  '/_search/courses': typeof SearchCoursesRouteWithChildren
  '/salary/_dialog': typeof SalaryDialogRouteWithChildren
  '/_search/courses/explore': typeof SearchCoursesExploreRouteWithChildren
  '/_search/courses/plan': typeof SearchCoursesPlanRouteWithChildren
  '/salary/_dialog/_form': typeof SalaryDialogFormRouteWithChildren
  '/salary/_dialog/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/_dialog/drafts': typeof SalaryDialogDraftsRoute
  '/salary/_dialog/submissions': typeof SalaryDialogSubmissionsRoute
  '/_search/courses/explore/$course_id': typeof SearchCoursesExploreCourse_idRoute
  '/_search/courses/plan/$course_id': typeof SearchCoursesPlanCourse_idRoute
  '/salary/_dialog/_form/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/_dialog/_form/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/_dialog/_form/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/salary'
    | '/courses'
    | '/courses/explore'
    | '/courses/plan'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/courses/explore/$course_id'
    | '/courses/plan/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/salary'
    | '/courses'
    | '/courses/explore'
    | '/courses/plan'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/courses/explore/$course_id'
    | '/courses/plan/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  id:
    | '__root__'
    | '/'
    | '/_search'
    | '/salary'
    | '/_search/courses'
    | '/salary/_dialog'
    | '/_search/courses/explore'
    | '/_search/courses/plan'
    | '/salary/_dialog/_form'
    | '/salary/_dialog/auto-fill'
    | '/salary/_dialog/drafts'
    | '/salary/_dialog/submissions'
    | '/_search/courses/explore/$course_id'
    | '/_search/courses/plan/$course_id'
    | '/salary/_dialog/_form/report'
    | '/salary/_dialog/_form/report/{-$idx}'
    | '/salary/_dialog/_form/reported/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRouteWithChildren
  SalaryRoute: typeof SalaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_search': {
      id: '/_search'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary/_dialog': {
      id: '/salary/_dialog'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogRouteImport
      parentRoute: typeof SalaryRoute
    }
    '/_search/courses': {
      id: '/_search/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof SearchCoursesRouteImport
      parentRoute: typeof SearchRoute
    }
    '/salary/_dialog/submissions': {
      id: '/salary/_dialog/submissions'
      path: '/submissions'
      fullPath: '/salary/submissions'
      preLoaderRoute: typeof SalaryDialogSubmissionsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/drafts': {
      id: '/salary/_dialog/drafts'
      path: '/drafts'
      fullPath: '/salary/drafts'
      preLoaderRoute: typeof SalaryDialogDraftsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/auto-fill': {
      id: '/salary/_dialog/auto-fill'
      path: '/auto-fill'
      fullPath: '/salary/auto-fill'
      preLoaderRoute: typeof SalaryDialogAutoFillRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/_form': {
      id: '/salary/_dialog/_form'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogFormRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/_search/courses/plan': {
      id: '/_search/courses/plan'
      path: '/plan'
      fullPath: '/courses/plan'
      preLoaderRoute: typeof SearchCoursesPlanRouteImport
      parentRoute: typeof SearchCoursesRoute
    }
    '/_search/courses/explore': {
      id: '/_search/courses/explore'
      path: '/explore'
      fullPath: '/courses/explore'
      preLoaderRoute: typeof SearchCoursesExploreRouteImport
      parentRoute: typeof SearchCoursesRoute
    }
    '/salary/_dialog/_form/report': {
      id: '/salary/_dialog/_form/report'
      path: '/report'
      fullPath: '/salary/report'
      preLoaderRoute: typeof SalaryDialogFormReportRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/_search/courses/plan/$course_id': {
      id: '/_search/courses/plan/$course_id'
      path: '/$course_id'
      fullPath: '/courses/plan/$course_id'
      preLoaderRoute: typeof SearchCoursesPlanCourse_idRouteImport
      parentRoute: typeof SearchCoursesPlanRoute
    }
    '/_search/courses/explore/$course_id': {
      id: '/_search/courses/explore/$course_id'
      path: '/$course_id'
      fullPath: '/courses/explore/$course_id'
      preLoaderRoute: typeof SearchCoursesExploreCourse_idRouteImport
      parentRoute: typeof SearchCoursesExploreRoute
    }
    '/salary/_dialog/_form/reported/$key': {
      id: '/salary/_dialog/_form/reported/$key'
      path: '/reported/$key'
      fullPath: '/salary/reported/$key'
      preLoaderRoute: typeof SalaryDialogFormReportedKeyRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/salary/_dialog/_form/report/{-$idx}': {
      id: '/salary/_dialog/_form/report/{-$idx}'
      path: '/{-$idx}'
      fullPath: '/salary/report/{-$idx}'
      preLoaderRoute: typeof SalaryDialogFormReportChar123IdxChar125RouteImport
      parentRoute: typeof SalaryDialogFormReportRoute
    }
  }
}

interface SearchCoursesExploreRouteChildren {
  SearchCoursesExploreCourse_idRoute: typeof SearchCoursesExploreCourse_idRoute
}

const SearchCoursesExploreRouteChildren: SearchCoursesExploreRouteChildren = {
  SearchCoursesExploreCourse_idRoute: SearchCoursesExploreCourse_idRoute,
}

const SearchCoursesExploreRouteWithChildren =
  SearchCoursesExploreRoute._addFileChildren(SearchCoursesExploreRouteChildren)

interface SearchCoursesPlanRouteChildren {
  SearchCoursesPlanCourse_idRoute: typeof SearchCoursesPlanCourse_idRoute
}

const SearchCoursesPlanRouteChildren: SearchCoursesPlanRouteChildren = {
  SearchCoursesPlanCourse_idRoute: SearchCoursesPlanCourse_idRoute,
}

const SearchCoursesPlanRouteWithChildren =
  SearchCoursesPlanRoute._addFileChildren(SearchCoursesPlanRouteChildren)

interface SearchCoursesRouteChildren {
  SearchCoursesExploreRoute: typeof SearchCoursesExploreRouteWithChildren
  SearchCoursesPlanRoute: typeof SearchCoursesPlanRouteWithChildren
}

const SearchCoursesRouteChildren: SearchCoursesRouteChildren = {
  SearchCoursesExploreRoute: SearchCoursesExploreRouteWithChildren,
  SearchCoursesPlanRoute: SearchCoursesPlanRouteWithChildren,
}

const SearchCoursesRouteWithChildren = SearchCoursesRoute._addFileChildren(
  SearchCoursesRouteChildren,
)

interface SearchRouteChildren {
  SearchCoursesRoute: typeof SearchCoursesRouteWithChildren
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchCoursesRoute: SearchCoursesRouteWithChildren,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface SalaryDialogFormReportRouteChildren {
  SalaryDialogFormReportChar123IdxChar125Route: typeof SalaryDialogFormReportChar123IdxChar125Route
}

const SalaryDialogFormReportRouteChildren: SalaryDialogFormReportRouteChildren =
  {
    SalaryDialogFormReportChar123IdxChar125Route:
      SalaryDialogFormReportChar123IdxChar125Route,
  }

const SalaryDialogFormReportRouteWithChildren =
  SalaryDialogFormReportRoute._addFileChildren(
    SalaryDialogFormReportRouteChildren,
  )

interface SalaryDialogFormRouteChildren {
  SalaryDialogFormReportRoute: typeof SalaryDialogFormReportRouteWithChildren
  SalaryDialogFormReportedKeyRoute: typeof SalaryDialogFormReportedKeyRoute
}

const SalaryDialogFormRouteChildren: SalaryDialogFormRouteChildren = {
  SalaryDialogFormReportRoute: SalaryDialogFormReportRouteWithChildren,
  SalaryDialogFormReportedKeyRoute: SalaryDialogFormReportedKeyRoute,
}

const SalaryDialogFormRouteWithChildren =
  SalaryDialogFormRoute._addFileChildren(SalaryDialogFormRouteChildren)

interface SalaryDialogRouteChildren {
  SalaryDialogFormRoute: typeof SalaryDialogFormRouteWithChildren
  SalaryDialogAutoFillRoute: typeof SalaryDialogAutoFillRoute
  SalaryDialogDraftsRoute: typeof SalaryDialogDraftsRoute
  SalaryDialogSubmissionsRoute: typeof SalaryDialogSubmissionsRoute
}

const SalaryDialogRouteChildren: SalaryDialogRouteChildren = {
  SalaryDialogFormRoute: SalaryDialogFormRouteWithChildren,
  SalaryDialogAutoFillRoute: SalaryDialogAutoFillRoute,
  SalaryDialogDraftsRoute: SalaryDialogDraftsRoute,
  SalaryDialogSubmissionsRoute: SalaryDialogSubmissionsRoute,
}

const SalaryDialogRouteWithChildren = SalaryDialogRoute._addFileChildren(
  SalaryDialogRouteChildren,
)

interface SalaryRouteChildren {
  SalaryDialogRoute: typeof SalaryDialogRouteWithChildren
}

const SalaryRouteChildren: SalaryRouteChildren = {
  SalaryDialogRoute: SalaryDialogRouteWithChildren,
}

const SalaryRouteWithChildren =
  SalaryRoute._addFileChildren(SalaryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRouteWithChildren,
  SalaryRoute: SalaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
