/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ProfessorsRouteImport } from './routes/professors'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as SalaryDialogRouteImport } from './routes/salary/_dialog'
import { Route as ProfessorsProfessor_idRouteImport } from './routes/professors/$professor_id'
import { Route as CoursesProfileRouteImport } from './routes/courses/profile'
import { Route as CoursesPlanRouteImport } from './routes/courses/plan'
import { Route as CoursesExploreRouteImport } from './routes/courses/explore'
import { Route as CompaniesCompany_idRouteImport } from './routes/companies/$company_id'
import { Route as CoursesPlanIndexRouteImport } from './routes/courses/plan/index'
import { Route as CompaniesCompany_idIndexRouteImport } from './routes/companies/$company_id/index'
import { Route as SalaryDialogSubmissionsRouteImport } from './routes/salary/_dialog/submissions'
import { Route as SalaryDialogDraftsRouteImport } from './routes/salary/_dialog/drafts'
import { Route as SalaryDialogAutoFillRouteImport } from './routes/salary/_dialog/auto-fill'
import { Route as SalaryDialogFormRouteImport } from './routes/salary/_dialog/_form'
import { Route as CoursesProfileCourse_idRouteImport } from './routes/courses/profile/$course_id'
import { Route as CoursesPlanTerm_idRouteImport } from './routes/courses/plan/$term_id'
import { Route as CoursesExploreCourse_idRouteImport } from './routes/courses/explore/$course_id'
import { Route as CompaniesCompany_idReviewsRouteImport } from './routes/companies/$company_id/reviews'
import { Route as CompaniesCompany_idPositionsRouteImport } from './routes/companies/$company_id/positions'
import { Route as CompaniesCompany_idPosition_idRouteImport } from './routes/companies/$company_id/$position_id'
import { Route as SalaryDialogFormReportRouteImport } from './routes/salary/_dialog/_form/report'
import { Route as CoursesPlanTerm_idCourse_idRouteImport } from './routes/courses/plan/$term_id/$course_id'
import { Route as SalaryDialogFormReportedKeyRouteImport } from './routes/salary/_dialog/_form/reported.$key'
import { Route as SalaryDialogFormReportChar123IdxChar125RouteImport } from './routes/salary/_dialog/_form/report.{-$idx}'

const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsRoute = ProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorsRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const SalaryDialogRoute = SalaryDialogRouteImport.update({
  id: '/_dialog',
  getParentRoute: () => SalaryRoute,
} as any)
const ProfessorsProfessor_idRoute = ProfessorsProfessor_idRouteImport.update({
  id: '/$professor_id',
  path: '/$professor_id',
  getParentRoute: () => ProfessorsRoute,
} as any)
const CoursesProfileRoute = CoursesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesPlanRoute = CoursesPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesExploreRoute = CoursesExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => CoursesRoute,
} as any)
const CompaniesCompany_idRoute = CompaniesCompany_idRouteImport.update({
  id: '/$company_id',
  path: '/$company_id',
  getParentRoute: () => CompaniesRoute,
} as any)
const CoursesPlanIndexRoute = CoursesPlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesPlanRoute,
} as any)
const CompaniesCompany_idIndexRoute =
  CompaniesCompany_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompaniesCompany_idRoute,
  } as any)
const SalaryDialogSubmissionsRoute = SalaryDialogSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogDraftsRoute = SalaryDialogDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogAutoFillRoute = SalaryDialogAutoFillRouteImport.update({
  id: '/auto-fill',
  path: '/auto-fill',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogFormRoute = SalaryDialogFormRouteImport.update({
  id: '/_form',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const CoursesProfileCourse_idRoute = CoursesProfileCourse_idRouteImport.update({
  id: '/$course_id',
  path: '/$course_id',
  getParentRoute: () => CoursesProfileRoute,
} as any)
const CoursesPlanTerm_idRoute = CoursesPlanTerm_idRouteImport.update({
  id: '/$term_id',
  path: '/$term_id',
  getParentRoute: () => CoursesPlanRoute,
} as any)
const CoursesExploreCourse_idRoute = CoursesExploreCourse_idRouteImport.update({
  id: '/$course_id',
  path: '/$course_id',
  getParentRoute: () => CoursesExploreRoute,
} as any)
const CompaniesCompany_idReviewsRoute =
  CompaniesCompany_idReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => CompaniesCompany_idRoute,
  } as any)
const CompaniesCompany_idPositionsRoute =
  CompaniesCompany_idPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => CompaniesCompany_idRoute,
  } as any)
const CompaniesCompany_idPosition_idRoute =
  CompaniesCompany_idPosition_idRouteImport.update({
    id: '/$position_id',
    path: '/$position_id',
    getParentRoute: () => CompaniesCompany_idRoute,
  } as any)
const SalaryDialogFormReportRoute = SalaryDialogFormReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SalaryDialogFormRoute,
} as any)
const CoursesPlanTerm_idCourse_idRoute =
  CoursesPlanTerm_idCourse_idRouteImport.update({
    id: '/$course_id',
    path: '/$course_id',
    getParentRoute: () => CoursesPlanTerm_idRoute,
  } as any)
const SalaryDialogFormReportedKeyRoute =
  SalaryDialogFormReportedKeyRouteImport.update({
    id: '/reported/$key',
    path: '/reported/$key',
    getParentRoute: () => SalaryDialogFormRoute,
  } as any)
const SalaryDialogFormReportChar123IdxChar125Route =
  SalaryDialogFormReportChar123IdxChar125RouteImport.update({
    id: '/{-$idx}',
    path: '/{-$idx}',
    getParentRoute: () => SalaryDialogFormReportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/professors': typeof ProfessorsRouteWithChildren
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/companies/$company_id': typeof CompaniesCompany_idRouteWithChildren
  '/courses/explore': typeof CoursesExploreRouteWithChildren
  '/courses/plan': typeof CoursesPlanRouteWithChildren
  '/courses/profile': typeof CoursesProfileRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/companies/': typeof CompaniesIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/companies/$company_id/$position_id': typeof CompaniesCompany_idPosition_idRoute
  '/companies/$company_id/positions': typeof CompaniesCompany_idPositionsRoute
  '/companies/$company_id/reviews': typeof CompaniesCompany_idReviewsRoute
  '/courses/explore/$course_id': typeof CoursesExploreCourse_idRoute
  '/courses/plan/$term_id': typeof CoursesPlanTerm_idRouteWithChildren
  '/courses/profile/$course_id': typeof CoursesProfileCourse_idRoute
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/companies/$company_id/': typeof CompaniesCompany_idIndexRoute
  '/courses/plan/': typeof CoursesPlanIndexRoute
  '/courses/plan/$term_id/$course_id': typeof CoursesPlanTerm_idCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/salary': typeof SalaryDialogFormRouteWithChildren
  '/courses/explore': typeof CoursesExploreRouteWithChildren
  '/courses/profile': typeof CoursesProfileRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/companies': typeof CompaniesIndexRoute
  '/professors': typeof ProfessorsIndexRoute
  '/companies/$company_id/$position_id': typeof CompaniesCompany_idPosition_idRoute
  '/companies/$company_id/positions': typeof CompaniesCompany_idPositionsRoute
  '/companies/$company_id/reviews': typeof CompaniesCompany_idReviewsRoute
  '/courses/explore/$course_id': typeof CoursesExploreCourse_idRoute
  '/courses/plan/$term_id': typeof CoursesPlanTerm_idRouteWithChildren
  '/courses/profile/$course_id': typeof CoursesProfileCourse_idRoute
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/submissions': typeof SalaryDialogSubmissionsRoute
  '/companies/$company_id': typeof CompaniesCompany_idIndexRoute
  '/courses/plan': typeof CoursesPlanIndexRoute
  '/courses/plan/$term_id/$course_id': typeof CoursesPlanTerm_idCourse_idRoute
  '/salary/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/professors': typeof ProfessorsRouteWithChildren
  '/salary': typeof SalaryRouteWithChildren
  '/companies/$company_id': typeof CompaniesCompany_idRouteWithChildren
  '/courses/explore': typeof CoursesExploreRouteWithChildren
  '/courses/plan': typeof CoursesPlanRouteWithChildren
  '/courses/profile': typeof CoursesProfileRouteWithChildren
  '/professors/$professor_id': typeof ProfessorsProfessor_idRoute
  '/salary/_dialog': typeof SalaryDialogRouteWithChildren
  '/companies/': typeof CompaniesIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/companies/$company_id/$position_id': typeof CompaniesCompany_idPosition_idRoute
  '/companies/$company_id/positions': typeof CompaniesCompany_idPositionsRoute
  '/companies/$company_id/reviews': typeof CompaniesCompany_idReviewsRoute
  '/courses/explore/$course_id': typeof CoursesExploreCourse_idRoute
  '/courses/plan/$term_id': typeof CoursesPlanTerm_idRouteWithChildren
  '/courses/profile/$course_id': typeof CoursesProfileCourse_idRoute
  '/salary/_dialog/_form': typeof SalaryDialogFormRouteWithChildren
  '/salary/_dialog/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/_dialog/drafts': typeof SalaryDialogDraftsRoute
  '/salary/_dialog/submissions': typeof SalaryDialogSubmissionsRoute
  '/companies/$company_id/': typeof CompaniesCompany_idIndexRoute
  '/courses/plan/': typeof CoursesPlanIndexRoute
  '/courses/plan/$term_id/$course_id': typeof CoursesPlanTerm_idCourse_idRoute
  '/salary/_dialog/_form/report': typeof SalaryDialogFormReportRouteWithChildren
  '/salary/_dialog/_form/report/{-$idx}': typeof SalaryDialogFormReportChar123IdxChar125Route
  '/salary/_dialog/_form/reported/$key': typeof SalaryDialogFormReportedKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/courses'
    | '/professors'
    | '/salary'
    | '/companies/$company_id'
    | '/courses/explore'
    | '/courses/plan'
    | '/courses/profile'
    | '/professors/$professor_id'
    | '/companies/'
    | '/professors/'
    | '/companies/$company_id/$position_id'
    | '/companies/$company_id/positions'
    | '/companies/$company_id/reviews'
    | '/courses/explore/$course_id'
    | '/courses/plan/$term_id'
    | '/courses/profile/$course_id'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/companies/$company_id/'
    | '/courses/plan/'
    | '/courses/plan/$term_id/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/salary'
    | '/courses/explore'
    | '/courses/profile'
    | '/professors/$professor_id'
    | '/companies'
    | '/professors'
    | '/companies/$company_id/$position_id'
    | '/companies/$company_id/positions'
    | '/companies/$company_id/reviews'
    | '/courses/explore/$course_id'
    | '/courses/plan/$term_id'
    | '/courses/profile/$course_id'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/submissions'
    | '/companies/$company_id'
    | '/courses/plan'
    | '/courses/plan/$term_id/$course_id'
    | '/salary/report'
    | '/salary/report/{-$idx}'
    | '/salary/reported/$key'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/courses'
    | '/professors'
    | '/salary'
    | '/companies/$company_id'
    | '/courses/explore'
    | '/courses/plan'
    | '/courses/profile'
    | '/professors/$professor_id'
    | '/salary/_dialog'
    | '/companies/'
    | '/professors/'
    | '/companies/$company_id/$position_id'
    | '/companies/$company_id/positions'
    | '/companies/$company_id/reviews'
    | '/courses/explore/$course_id'
    | '/courses/plan/$term_id'
    | '/courses/profile/$course_id'
    | '/salary/_dialog/_form'
    | '/salary/_dialog/auto-fill'
    | '/salary/_dialog/drafts'
    | '/salary/_dialog/submissions'
    | '/companies/$company_id/'
    | '/courses/plan/'
    | '/courses/plan/$term_id/$course_id'
    | '/salary/_dialog/_form/report'
    | '/salary/_dialog/_form/report/{-$idx}'
    | '/salary/_dialog/_form/reported/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  ProfessorsRoute: typeof ProfessorsRouteWithChildren
  SalaryRoute: typeof SalaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors': {
      id: '/professors'
      path: '/professors'
      fullPath: '/professors'
      preLoaderRoute: typeof ProfessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof ProfessorsRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/salary/_dialog': {
      id: '/salary/_dialog'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogRouteImport
      parentRoute: typeof SalaryRoute
    }
    '/professors/$professor_id': {
      id: '/professors/$professor_id'
      path: '/$professor_id'
      fullPath: '/professors/$professor_id'
      preLoaderRoute: typeof ProfessorsProfessor_idRouteImport
      parentRoute: typeof ProfessorsRoute
    }
    '/courses/profile': {
      id: '/courses/profile'
      path: '/profile'
      fullPath: '/courses/profile'
      preLoaderRoute: typeof CoursesProfileRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/plan': {
      id: '/courses/plan'
      path: '/plan'
      fullPath: '/courses/plan'
      preLoaderRoute: typeof CoursesPlanRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/explore': {
      id: '/courses/explore'
      path: '/explore'
      fullPath: '/courses/explore'
      preLoaderRoute: typeof CoursesExploreRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/companies/$company_id': {
      id: '/companies/$company_id'
      path: '/$company_id'
      fullPath: '/companies/$company_id'
      preLoaderRoute: typeof CompaniesCompany_idRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/courses/plan/': {
      id: '/courses/plan/'
      path: '/'
      fullPath: '/courses/plan/'
      preLoaderRoute: typeof CoursesPlanIndexRouteImport
      parentRoute: typeof CoursesPlanRoute
    }
    '/companies/$company_id/': {
      id: '/companies/$company_id/'
      path: '/'
      fullPath: '/companies/$company_id/'
      preLoaderRoute: typeof CompaniesCompany_idIndexRouteImport
      parentRoute: typeof CompaniesCompany_idRoute
    }
    '/salary/_dialog/submissions': {
      id: '/salary/_dialog/submissions'
      path: '/submissions'
      fullPath: '/salary/submissions'
      preLoaderRoute: typeof SalaryDialogSubmissionsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/drafts': {
      id: '/salary/_dialog/drafts'
      path: '/drafts'
      fullPath: '/salary/drafts'
      preLoaderRoute: typeof SalaryDialogDraftsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/auto-fill': {
      id: '/salary/_dialog/auto-fill'
      path: '/auto-fill'
      fullPath: '/salary/auto-fill'
      preLoaderRoute: typeof SalaryDialogAutoFillRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/_form': {
      id: '/salary/_dialog/_form'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogFormRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/courses/profile/$course_id': {
      id: '/courses/profile/$course_id'
      path: '/$course_id'
      fullPath: '/courses/profile/$course_id'
      preLoaderRoute: typeof CoursesProfileCourse_idRouteImport
      parentRoute: typeof CoursesProfileRoute
    }
    '/courses/plan/$term_id': {
      id: '/courses/plan/$term_id'
      path: '/$term_id'
      fullPath: '/courses/plan/$term_id'
      preLoaderRoute: typeof CoursesPlanTerm_idRouteImport
      parentRoute: typeof CoursesPlanRoute
    }
    '/courses/explore/$course_id': {
      id: '/courses/explore/$course_id'
      path: '/$course_id'
      fullPath: '/courses/explore/$course_id'
      preLoaderRoute: typeof CoursesExploreCourse_idRouteImport
      parentRoute: typeof CoursesExploreRoute
    }
    '/companies/$company_id/reviews': {
      id: '/companies/$company_id/reviews'
      path: '/reviews'
      fullPath: '/companies/$company_id/reviews'
      preLoaderRoute: typeof CompaniesCompany_idReviewsRouteImport
      parentRoute: typeof CompaniesCompany_idRoute
    }
    '/companies/$company_id/positions': {
      id: '/companies/$company_id/positions'
      path: '/positions'
      fullPath: '/companies/$company_id/positions'
      preLoaderRoute: typeof CompaniesCompany_idPositionsRouteImport
      parentRoute: typeof CompaniesCompany_idRoute
    }
    '/companies/$company_id/$position_id': {
      id: '/companies/$company_id/$position_id'
      path: '/$position_id'
      fullPath: '/companies/$company_id/$position_id'
      preLoaderRoute: typeof CompaniesCompany_idPosition_idRouteImport
      parentRoute: typeof CompaniesCompany_idRoute
    }
    '/salary/_dialog/_form/report': {
      id: '/salary/_dialog/_form/report'
      path: '/report'
      fullPath: '/salary/report'
      preLoaderRoute: typeof SalaryDialogFormReportRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/courses/plan/$term_id/$course_id': {
      id: '/courses/plan/$term_id/$course_id'
      path: '/$course_id'
      fullPath: '/courses/plan/$term_id/$course_id'
      preLoaderRoute: typeof CoursesPlanTerm_idCourse_idRouteImport
      parentRoute: typeof CoursesPlanTerm_idRoute
    }
    '/salary/_dialog/_form/reported/$key': {
      id: '/salary/_dialog/_form/reported/$key'
      path: '/reported/$key'
      fullPath: '/salary/reported/$key'
      preLoaderRoute: typeof SalaryDialogFormReportedKeyRouteImport
      parentRoute: typeof SalaryDialogFormRoute
    }
    '/salary/_dialog/_form/report/{-$idx}': {
      id: '/salary/_dialog/_form/report/{-$idx}'
      path: '/{-$idx}'
      fullPath: '/salary/report/{-$idx}'
      preLoaderRoute: typeof SalaryDialogFormReportChar123IdxChar125RouteImport
      parentRoute: typeof SalaryDialogFormReportRoute
    }
  }
}

interface CompaniesCompany_idRouteChildren {
  CompaniesCompany_idPosition_idRoute: typeof CompaniesCompany_idPosition_idRoute
  CompaniesCompany_idPositionsRoute: typeof CompaniesCompany_idPositionsRoute
  CompaniesCompany_idReviewsRoute: typeof CompaniesCompany_idReviewsRoute
  CompaniesCompany_idIndexRoute: typeof CompaniesCompany_idIndexRoute
}

const CompaniesCompany_idRouteChildren: CompaniesCompany_idRouteChildren = {
  CompaniesCompany_idPosition_idRoute: CompaniesCompany_idPosition_idRoute,
  CompaniesCompany_idPositionsRoute: CompaniesCompany_idPositionsRoute,
  CompaniesCompany_idReviewsRoute: CompaniesCompany_idReviewsRoute,
  CompaniesCompany_idIndexRoute: CompaniesCompany_idIndexRoute,
}

const CompaniesCompany_idRouteWithChildren =
  CompaniesCompany_idRoute._addFileChildren(CompaniesCompany_idRouteChildren)

interface CompaniesRouteChildren {
  CompaniesCompany_idRoute: typeof CompaniesCompany_idRouteWithChildren
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompany_idRoute: CompaniesCompany_idRouteWithChildren,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface CoursesExploreRouteChildren {
  CoursesExploreCourse_idRoute: typeof CoursesExploreCourse_idRoute
}

const CoursesExploreRouteChildren: CoursesExploreRouteChildren = {
  CoursesExploreCourse_idRoute: CoursesExploreCourse_idRoute,
}

const CoursesExploreRouteWithChildren = CoursesExploreRoute._addFileChildren(
  CoursesExploreRouteChildren,
)

interface CoursesPlanTerm_idRouteChildren {
  CoursesPlanTerm_idCourse_idRoute: typeof CoursesPlanTerm_idCourse_idRoute
}

const CoursesPlanTerm_idRouteChildren: CoursesPlanTerm_idRouteChildren = {
  CoursesPlanTerm_idCourse_idRoute: CoursesPlanTerm_idCourse_idRoute,
}

const CoursesPlanTerm_idRouteWithChildren =
  CoursesPlanTerm_idRoute._addFileChildren(CoursesPlanTerm_idRouteChildren)

interface CoursesPlanRouteChildren {
  CoursesPlanTerm_idRoute: typeof CoursesPlanTerm_idRouteWithChildren
  CoursesPlanIndexRoute: typeof CoursesPlanIndexRoute
}

const CoursesPlanRouteChildren: CoursesPlanRouteChildren = {
  CoursesPlanTerm_idRoute: CoursesPlanTerm_idRouteWithChildren,
  CoursesPlanIndexRoute: CoursesPlanIndexRoute,
}

const CoursesPlanRouteWithChildren = CoursesPlanRoute._addFileChildren(
  CoursesPlanRouteChildren,
)

interface CoursesProfileRouteChildren {
  CoursesProfileCourse_idRoute: typeof CoursesProfileCourse_idRoute
}

const CoursesProfileRouteChildren: CoursesProfileRouteChildren = {
  CoursesProfileCourse_idRoute: CoursesProfileCourse_idRoute,
}

const CoursesProfileRouteWithChildren = CoursesProfileRoute._addFileChildren(
  CoursesProfileRouteChildren,
)

interface CoursesRouteChildren {
  CoursesExploreRoute: typeof CoursesExploreRouteWithChildren
  CoursesPlanRoute: typeof CoursesPlanRouteWithChildren
  CoursesProfileRoute: typeof CoursesProfileRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesExploreRoute: CoursesExploreRouteWithChildren,
  CoursesPlanRoute: CoursesPlanRouteWithChildren,
  CoursesProfileRoute: CoursesProfileRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ProfessorsRouteChildren {
  ProfessorsProfessor_idRoute: typeof ProfessorsProfessor_idRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
}

const ProfessorsRouteChildren: ProfessorsRouteChildren = {
  ProfessorsProfessor_idRoute: ProfessorsProfessor_idRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
}

const ProfessorsRouteWithChildren = ProfessorsRoute._addFileChildren(
  ProfessorsRouteChildren,
)

interface SalaryDialogFormReportRouteChildren {
  SalaryDialogFormReportChar123IdxChar125Route: typeof SalaryDialogFormReportChar123IdxChar125Route
}

const SalaryDialogFormReportRouteChildren: SalaryDialogFormReportRouteChildren =
  {
    SalaryDialogFormReportChar123IdxChar125Route:
      SalaryDialogFormReportChar123IdxChar125Route,
  }

const SalaryDialogFormReportRouteWithChildren =
  SalaryDialogFormReportRoute._addFileChildren(
    SalaryDialogFormReportRouteChildren,
  )

interface SalaryDialogFormRouteChildren {
  SalaryDialogFormReportRoute: typeof SalaryDialogFormReportRouteWithChildren
  SalaryDialogFormReportedKeyRoute: typeof SalaryDialogFormReportedKeyRoute
}

const SalaryDialogFormRouteChildren: SalaryDialogFormRouteChildren = {
  SalaryDialogFormReportRoute: SalaryDialogFormReportRouteWithChildren,
  SalaryDialogFormReportedKeyRoute: SalaryDialogFormReportedKeyRoute,
}

const SalaryDialogFormRouteWithChildren =
  SalaryDialogFormRoute._addFileChildren(SalaryDialogFormRouteChildren)

interface SalaryDialogRouteChildren {
  SalaryDialogFormRoute: typeof SalaryDialogFormRouteWithChildren
  SalaryDialogAutoFillRoute: typeof SalaryDialogAutoFillRoute
  SalaryDialogDraftsRoute: typeof SalaryDialogDraftsRoute
  SalaryDialogSubmissionsRoute: typeof SalaryDialogSubmissionsRoute
}

const SalaryDialogRouteChildren: SalaryDialogRouteChildren = {
  SalaryDialogFormRoute: SalaryDialogFormRouteWithChildren,
  SalaryDialogAutoFillRoute: SalaryDialogAutoFillRoute,
  SalaryDialogDraftsRoute: SalaryDialogDraftsRoute,
  SalaryDialogSubmissionsRoute: SalaryDialogSubmissionsRoute,
}

const SalaryDialogRouteWithChildren = SalaryDialogRoute._addFileChildren(
  SalaryDialogRouteChildren,
)

interface SalaryRouteChildren {
  SalaryDialogRoute: typeof SalaryDialogRouteWithChildren
}

const SalaryRouteChildren: SalaryRouteChildren = {
  SalaryDialogRoute: SalaryDialogRouteWithChildren,
}

const SalaryRouteWithChildren =
  SalaryRoute._addFileChildren(SalaryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  ProfessorsRoute: ProfessorsRouteWithChildren,
  SalaryRoute: SalaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
