//export const UndergraduateMajor = [
//   'Accounting (BSBA)',
//   'Air Force ROTC',
//   'Animation & Visual Effects (BS)',
//   'Architectural Engineering (BSAE)',
//   'Architectural Studies (BS)',
//   'Architecture (BArch)',
//   'Army ROTC',
//   'Art History (BA)',
//   'Art History (BS)',
//   'Behavioral Economics, Business and Organizations (BS)',
//   'Biological Sciences (BS)',
//   'Biomedical Engineering (BS)',
//   'Business (General) (BSBA)',
//   'Business Undeclared',
//   'Business and Engineering (BSBAE)',
//   'Business Analytics (BSBA)',
//   'Business Administration (BSBA)',
//   'Business Law (BSBA)',
//   'Chemical Engineering (BSCHE)',
//   'Chemistry (BA)',
//   'Chemistry (BS)',
//   'Chemistry-Biochemistry Concentration (BS)',
//   'Civil Engineering (BSCIV)',
//   'Communication (BA)',
//   'Computer Engineering (BSCE)',
//   'Computer Science (BACS)',
//   'Computer Science (BSCS)',
//   'Computing and Security Technology (BSCST)',
//   'Construction Management (BSCMGT)',
//   'Criminology and Justice Studies (BS)',
//   'Culinary Arts & Science (BSCAS)',
//   'Custom-Designed Major (BS)',
//   'Dance (BS)',
//   'Dance - Part-time Professional (BS)',
//   'Data Science (BS)',
//   'Digital Media and Virtual Production (BS)',
//   'Economic Analysis (BAECON)',
//   'Economics (BSECON)',
//   'Economics and Business (BS)',
//   'Economics and Data Science (BSECDS)',
//   'Economics and Mathematics (BS)',
//   'Economics and Public Health (BS)',
//   'Educational Studies & Innovation (BS)',
//   'Education: Non-Certification (BS)',
//   'Electrical Engineering (BSEE)',
//   'Elementary Education (BS)',
//   'Engineering (BSE)',
//   'Engineering Technology (BSET)',
//   'Engineering Undeclared',
//   'English, Literary Studies Concentration (BA)',
//   'English, Writing Concentration (BA)',
//   'English, Secondary Education Concentration (BA)',
//   'Entertainment and Arts Management (BS)',
//   'Entrepreneurship and Innovation (BA)',
//   'Entrepreneurship & Innovation 3-year Option (BA)',
//   'Environmental Engineering (BSENE)',
//   'Environmental Science (BS)',
//   'Environmental Studies and Sustainability (BA)',
//   'Esport Business (BSBA)',
//   'Exercise Science (BS)',
//   'Fashion Design (BS)',
//   'Fashion Industry & Merchandising (BS)',
//   'Film & Television (BS)',
//   'Finance (BSBA)',
//   'First Year Exploratory Studies (Non-degree)',
//   'Game Design & Production (BS)',
//   'General Business (BSBA)',
//   'General Humanities and Social Sciences (Undeclared)',
//   'Global Public Health (BA)',
//   'Global Studies (BA) ',
//   'Graphic Design (BS)',
//   'Health Data Analytics (BS)',
//   'Health Sciences (BS)',
//   'Health Services Administration (BS)',
//   'History (BA)',
//   'Hospitality Management (BSHM)',
//   'Human Development and Counseling (BS)',
//   'Information Systems (BS)',
//   'Interdisciplinary Professional Studies (BS)',
//   'International Business (BSBA)',
//   'Interior Design (BS)',
//   'Law (BA)',
//   'Learning Sciences, Experience Design, and Technology',
//   'Management Information Systems (BSBA)',
//   'Marketing (BSBA)',
//   'Materials Science and Engineering (BSMSE)',
//   'Mathematical Statistics (BS)',
//   'Mathematics (BA)',
//   'Mathematics (BS)',
//   'Mechanical Engineering & Mechanics (BSME)',
//   'Music Industry (BS)',
//   'Navy ROTC',
//   'Neuroscience (BS)',
//   'Nursing (BSN)',
//   'Nursing: RN-MSN Bridge Program',
//   'Nutrition and Foods (BS)',
//   'Operations and Supply Chain Management (BSBA)',
//   'Organizational Management (co-major) (BSBA)',
//   'Philosophy (BA)',
//   'Philosophy, Politics and Economics (BA)',
//   'Photography (BS)',
//   'Physics (BS)',
//   'Political Science (BA)',
//   'Product Design (BS)',
//   'Psychology (BS)',
//   'Public Health (BS)',
//   'Real Estate Management and Development (BSBA)',
//   'ROTC (Air Force, Army, Navy)',
//   'Science (Undeclared)',
//   'Screenwriting and Playwriting (BS)',
//   'Sociology (BA)',
//   'Software Engineering (BS)',
//   'Special Education (PK-12) (BS)',
//   'Sport Business (BSBA)',
//   'Sustainability and Innovation (BS)',
//   'Teacher Education (BS)',
//   'Technology Innovation Management (co-major) (BS)',
//   'User Experience and Interaction Design (BS)',
//   'Westphal Studies Program (BS)',
//]);
//export const GraduateMinors = [
//   'Accounting',
//   'Arts Administration',
//   'Arts in Public Health',
//   'Bioinformatics',
//   'Biostatistics',
//   'Business',
//   'Business Analytics',
//   'Business Analytics Management',
//   'Change Leadership & Strategy',
//   'Clinical Research Organization and Management',
//   'Communication',
//   'Communication, Culture and Media',
//   'Complementary and Integrative Therapies (Advanced Study)',
//   'Computational Engineering',
//   'Computer Science',
//   'Creativity and Innovation',
//   'Digital Media',
//   'Digital Supply Chain Management',
//   'Drug Discovery and Development',
//   'Economic Data Analysis',
//   'Economics',
//   'Entrepreneurship and Innovation',
//   'Environmental and Occupational Health',
//   'Environmental Epidemiology',
//   'Finance',
//   'Global Health',
//   'Global and International Education',
//   'Health Administration',
//   'Healthcare Simulation',
//   'Higher Education Leadership',
//   'Human-Computer Interaction and User Experience',
//   'Infectious Disease and Population Health',
//   'Interdisciplinary Team-Oriented Creativity',
//   'Latino and Immigrant Health',
//   'Law',
//   'Leadership and Teams',
//   'Lesbian, Gay, Bisexual and Transgender (LGBT) Health',
//   'Marketing',
//   'Maternal and Child Health',
//   'Mind, Brain & Learning',
//   'Museum Leadership',
//   'Nonprofit Management: Public, Professional and Social Sectors',
//   'Nursing Education',
//   'Nursing Leadership in Health Systems Management',
//   'Operations Research',
//   'Pediatric Engineering',
//   'Pre-veterinary',
//   'Professional Studies',
//   'Program Monitoring and Evaluation',
//   'Project Management',
//   'Public Health Emergency Preparedness',
//   'Public Policy',
//   'Quality, Safety and Risk Management in Healthcare',
//   'Retail and Merchandising',
//   'Sport Management',
//   'Substance Use and Misuse',
//   'Sustainable Operations Management',
//   'Taxation',
//   'Undergraduate STEM Education',
//   'Urban Health',
//];

//export const UndergraduateMinors = [
//   'Accounting',
//   'Actuarial Science',
//   'Africana Studies',
//   'Animation and Visual Effects',
//   'Architectural Engineering',
//   'Architecture',
//   'Art History',
//   'Artificial Intelligence and Learning',
//   'Asian Studies',
//   'Astrophysics',
//   'Behavioral Economics and Business',
//   'Biochemistry',
//   'Bioinformatics',
//   'Biological Sciences',
//   'Biophysics',
//   'Bioscience and Society',
//   'Business Administration',
//   'Business Analytics',
//   'Business Consulting',
//   'Business Law',
//   'Chemical Engineering',
//   'Chemistry',
//   'Client Development and Customer Service',
//   'Climate Change',
//   'Communication',
//   'Computer Engineering',
//   'Computer Science',
//   'Computing Technology',
//   'Construction Management',
//   'Corporate Entrepreneurship',
//   'Crime Analysis and Digital Investigations',
//   'Criminal Justice',
//   'Culinary Arts',
//   'Dance',
//   'Data Science',
//   'DragonsTeach Certification Minor',
//   'DragonsTeach Middle Years Minor',
//   'DragonsTeach Middle Years Certification Minor',
//   'Ecology',
//   'Economics',
//   'Econometrics and Data Analytics',
//   'Education',
//   'Electrical Engineering',
//   'Engineering Leadership',
//   'Engineering Management',
//   'Engineering Policy Analysis',
//   'English',
//   'Entertainment & Arts Management',
//   'Entrepreneurship and Innovation',
//   'Environmental Engineering',
//   'Environmental Public Health',
//   'Environmental Sociology',
//   'Environmental Studies',
//   'Epidemiology',
//   'Esports',
//   'European Studies',
//   'Exercise Science',
//   'Film & Television Production',
//   'Film & Television Studies',
//   'Film Studies',
//   'Finance',
//   'Financial Technology',
//   'Fine Arts',
//   'Food Science',
//   'Food Studies',
//   'French',
//   'Game Design and Production',
//   'Gender and Sexuality Studies',
//   'Geoscience',
//   'Global Engineering',
//   'Global Public Health',
//   'Global Studies',
//   'Graphic Design',
//   'Green Energy and Sustainability',
//   'Health and Social Justice',
//   'Health Data Analytics',
//   'Health Services Administration',
//   'History',
//   'History of Capitalism',
//   'Hospitality Management',
//   'Human Computer Interaction',
//   'Immune Engineering',
//   'Information Systems',
//   'Interdisciplinary Problem Solving',
//   'International Business',
//   'Japanese',
//   'Jazz and African-American Music',
//   'Jewish Studies',
//   'Justice Studies',
//   'Law',
//   'Linguistics',
//   'Management Information Systems',
//   'Marketing',
//   'Materials Science and Engineering',
//   'Mathematics',
//   'Mechanical Engineering and Mechanics',
//   'Medical Sociology',
//   'Merchandising',
//   'Middle East and North Africa Studies',
//   'Military Science',
//   'Music',
//   'Music Performance',
//   'Music Theory and Composition',
//   'Neuroscience',
//   'Nonprofit Communication',
//   'Nutrition',
//   'Operations and Supply Chain Management',
//   'Organizational Management',
//   'Performing Arts',
//   'Philosophy',
//   'Photography',
//   'Physics',
//   'Playwriting',
//   'Poetry, Biblio and Expressive Writing Facilitation',
//   'Politics',
//   'Product Design',
//   'Project Management',
//   'Psychiatric Rehabilitation',
//   'Psychology',
//   'Public Health',
//   'Real Estate Management and Development',
//   'Religious Studies',
//   'Robotics and Automation',
//   'Science, Technology and Society',
//   'Screenwriting',
//   'Security Technology',
//   'Social Entrepreneurship',
//   'Sociology',
//   'Software Engineering',
//   'Somatics',
//   'Spanish',
//   'Sport Coaching Leadership',
//   'Sport Management',
//   'Sport Regulation & Compliance',
//   'STEM Education',
//   'Sustainability in the Built Environment',
//   'Systems Engineering',
//   'Technology Innovation Management',
//   'Theatre',
//   'User Experience and Interaction Design',
//   'Virtual Reality & Immersive Media',
//   'War and Society',
//   'Writing',
//];

//export const graduateMajors = [
//   'Academic Medicine (MS) ',
//   'Accounting (MS)',
//   'Accounting Analytics (MBA)',
//   'Addictions Counseling (MS) ',
//   'American Legal Practice (LLM)',
//   'Applied Behavior Analysis (MS)',
//   'Applied Behavior Analysis and Special Education (MS)',
//   'Applied Cognitive and Brain Sciences (PhD)',
//   'Applied Learning, Leadership and Innovation (EdS)',
//   'Architectural Engineering (MSAE)',
//   'Architectural Engineering (PhD)',
//   'Art Therapy and Counseling (MA)',
//   'Artificial Intelligence and Machine Learning (MSAIML)',
//   'Arts Administration (MS)',
//   'Biochemistry of Health & Disease (MS)',
//   'Biochemistry of Health & Disease (PhD)',
//   'Bioinformatics (MS)',
//   'Biological Sciences (MS: College of Arts and Sciences)',
//   'Biological Sciences (PhD: College of Arts and Sciences)',
//   'Biomedical Engineering (MS: School of Biomedical Engineering, Science and Health Systems)',
//   'Biomedical Engineering (PhD: School of Biomedical Engineering, Science and Health Systems)',
//   'Biomedical Science (MS: School of Biomedical Engineering, Science and Health Systems)',
//   'Biomedical Science (PhD: School of Biomedical Engineering, Science and Health Systems)',
//   'Biomedical Studies (MS)',
//   'Biomedicine and Business (MS)',
//   'Biomedicine and Cell & Gene Therapy (MS)',
//   'Biomedicine and Digital Media (MS)',
//   'Biomedicine and Entrepreneurship (MS)',
//   'Biomedicine and Law (MS)',
//   'Biostatistics (MS)',
//   'Biostatistics (PhD)',
//   'Biotechnology (MS)',
//   'Business Administration (DBA)',
//   'Business Administration (PhD)',
//   'Business Analytics (MBA)',
//   'Business Analytics (MS)',
//   'Business Customized (MBA)',
//   'Business Information Technology (MSBIT)',
//   'Cancer Biology (MS)',
//   'Chemical Engineering (MS)',
//   'Chemical Engineering (PhD)',
//   'Chemistry (MS)',
//   'Chemistry (PhD)',
//   'Civil Engineering (MSCE)',
//   'Civil Engineering (PhD)',
//   'Clinical Research for Health Professionals (MS)',
//   'Clinical Research Organization & Management (MS)',
//   'Communication, Culture and Media (MS)',
//   'Communication, Culture and Media (PhD)',
//   'Community Health and Prevention (MPH)',
//   'Community Health and Prevention (PhD)',
//   'Complementary and Integrative Health (MS)',
//   'Computer Engineering (MS)',
//   'Computer Engineering (PhD)',
//   'Computer Security and Privacy (MS)',
//   'Computer Science (MSCS)',
//   'Computer Science (PhD)',
//   'Construction Management (MS)',
//   'Corporate Sustainability and Social Impact (MBA)',
//   'Couple and Family Therapy (DCFT)',
//   'Couple and Family Therapy (PhD)',
//   'Creative Arts in Therapy (PhD)',
//   'Creative Education and Entrepreneurship (MS)',
//   'Creative Writing (MFA)',
//   'Creativity and Innovation (MS)',
//   'Culinary & Food Science (MS)',
//   'Cyber Law and Data Privacy (LLM) ',
//   'Cyber Law and Data Privacy (LLM) ',
//   'Cybersecurity (MS)',
//   'Dance/Movement Therapy and Counseling (MA)',
//   'Data Science (MS)',
//   'Design (MS)',
//   'Digital Marketing Technology (MSM)',
//   'Digital Media (MS)',
//   'Digital Media (PhD)',
//   'Drexel Pathway to Medical School (MS)',
//   'Drug Discovery and Development (MS)',
//   'Ecology, Evolution, and Earth Systems (MS)',
//   'Ecology, Evolution, and Earth Systems (PhD)',
//   'Economics (MBA)',
//   'Economics (MSECON)',
//   'Economics (PhD)',
//   'Economics and Computer Science (MSECCS)',
//   'Education (PhD)',
//   'Education Improvement and Transformation (MS)',
//   'Educational Administration (MS)',
//   'Educational Leadership and Management (EdD)',
//   'Effective Leadership (MBA)',
//   'Electrical Engineering (MS)',
//   'Electrical Engineering (PhD)',
//   'Engineering (ME)',
//   'Engineering Management (MS)',
//   'Engineering Technology (MS) ',
//   'Entrepreneurship and Innovation (MS)',
//   'Environmental and Occupational Health (MPH)',
//   'Environmental and Occupational Health (PhD)',
//   'Environmental and Occupational Health Sciences (MS)',
//   'Environmental Engineering (MS)',
//   'Environmental Engineering (PhD)',
//   'Environmental Policy (MSEP)',
//   'Epidemiology (MS)',
//   'Epidemiology (MPH)',
//   'Epidemiology (PhD)',
//   'Family/Individual Across the Lifespan Nurse Practitioner (MSN)',
//   'Family/Individual Across the Lifespan with Emergency Specialization (MSN)',
//   'Family Therapy (MFT)',
//   'Fashion Design (MS)',
//   'Finance (MBA)',
//   'General Business (MBA)',
//   'Global Financial Regulation (LLM) ',
//   'Global Financial Regulation (LLM) ',
//   'Global Health (MS)',
//   'Global Health (MPH)',
//   'Health and Rehabilitation Sciences (MS)',
//   'Health and Rehabilitation Sciences (PhD)',
//   'Health Administration (MHA)',
//   'Health Care and Pharmaceutical Compliance (LLM) ',
//   'Health Care and Pharmaceutical Compliance (LLM) ',
//   'Health Management and Policy (MPH)',
//   'Health Sciences (DHSc) ',
//   'Health Services Research and Policy (PhD)',
//   'Healthcare Simulation (MS) ',
//   'Higher Education Leadership (MS)',
//   'Histotechnology (MS)',
//   'Human Nutrition (MS)',
//   'Human-Computer Interaction and User Experience (MS)',
//   'Human Resource Development (MS)',
//   'Immunology (MS)',
//   'Infection Prevention and Control (MS)',
//   'Infectious Disease (MS)',
//   'Information Science (PhD)',
//   'Information Systems (MSIS)',
//   'Integrated Biomedical Engineering and Business (MS)',
//   'Intensive Medical Sciences (MS)',
//   'Interdisciplinary Health Sciences (MS)',
//   'Interior Architecture (MS)',
//   'Interior Architecture and Design (MS)',
//   'International Commercial Law (LLM)',
//   'Internet of Things (MS)',
//   'Juris Doctor (JD)',
//   'Laboratory Animal Science (MLAS)',
//   'Law (JD)',
//   'Law (JD) / Public Health (MPH)',
//   'Learning Technologies (MS)',
//   'Legal Studies (MLS) ',
//   'Legal Studies (MLS) ',
//   'Library and Information Science (MSLIS)',
//   'Machine Learning Engineering (MSMLE)',
//   'Marketing (MBA)',
//   'Marketing Leadership (MSM)',
//   'Marketing Technology and Analytics (MBA)',
//   'Marketing Technology and Analytics (MSM)',
//   'Materials Science and Engineering (MS)',
//   'Materials Science and Engineering (PhD)',
//   'Mathematics (MS)',
//   'Mathematics (PhD)',
//   'Mechanical Engineering and Mechanics (MS)',
//   'Mechanical Engineering and Mechanics (PhD)',
//   'Medical Science (MS)',
//   'Medical Science (MD/MS)',
//   'Medicine (MD)',
//   'Medicine (MD) / PhD',
//   'Microbiology and Immunology (MS)',
//   'Microbiology and Immunology (PhD)',
//   'Molecular Basis of Cancer (MS)',
//   'Molecular and Cell Biology and Genetics (MS)',
//   'Molecular and Cell Biology and Genetics (PhD)',
//   'Molecular Medicine (MS)',
//   'Music Therapy and Counseling (MA)',
//   'Nanomaterials (MS)',
//   'Neuroscience (MS)',
//   'Neuroscience (PhD)',
//   'Nonprofit Management: Public, Professional & Social Sectors (MS)',
//   'Nurse Anesthesia (DNP)',
//   'Nurse Practitioner (DNP)',
//   'Nursing - Advanced Role (MSN)',
//   'Clinical Nurse Leader ',
//   'Healthcare Simulation ',
//   'Nursing Education',
//   'Nursing Leadership and Health Systems Management',
//   'MSN-Bridge Program',
//   'Nursing - Nurse Practitioner (MSN)',
//   'Adult-Gerontology Acute Care Nurse Practitioner',
//   'Adult-Gerontology Primary Care Nurse Practitioner',
//   'Family/Individual Across the Life Span Nurse Practitioner',
//   'Pediatric Acute Care Nurse Practitioner',
//   'Pediatric Primary Care Nurse Practitioner',
//   'Pediatric Acute Care and Pediatric Primary Care Dual Option Nurse Practitioner',
//   'Public Health Nursing',
//   'Psychiatric Mental Health Nurse Practitioner',
//   "Women's Health/Gender Related Nurse Practitioner",
//   'Nursing: MSN/PhD joint degree (MSN/PhD)',
//   'Nursing (PhD)',
//   'Nursing Leadership in Health Systems Management (MSN)',
//   'Business Administration (MBA)',
//   'Nursing Practice (DNP)',
//   'Nutrition and Dietetics (MS)',
//   'Nutrition Sciences (PhD)',
//   "Pathologists' Assistant (MS)",
//   'Peace Engineering (MS)',
//   'Pharmacology & Physiology (MS)',
//   'Pharmacology & Physiology (PhD)',
//   'Physical Therapy (DPT)',
//   'Physician Assistant (MHS)',
//   'Physics (MS)',
//   'Physics (PhD)',
//   'Professional Studies (MS)',
//   'Project Management (MBA)',
//   'Psychology (MS)',
//   'Psychology: Applied Cognitive and Brain Sciences (PhD)',
//   'Psychology: Clinical Psychology (PhD)',
//   'Public Health - Executive Program (MPH)',
//   'Public Policy (MS)',
//   'Public Policy (MS) / Juris Doctor (JD)',
//   'Publishing (MA) ',
//   'Quality, Safety and Risk Management in Health Care (MS)',
//   'Quality, Safety and Risk Management in Health Care (MSN)',
//   'Rehabilitation Sciences (MHS) ',
//   'Retail & Merchandising (MS)',
//   'Robotics and Autonomy (MS)',
//   'School Psychology (EdS)',
//   'Science, Technology, and Society (MS) ',
//   'Software Engineering (MSSE)',
//   'Special Education (MS)',
//   'Sport Business (MS)',
//   'Strategic and Digital Communication (MS)',
//   'Strategic Technology & Innovation Management (MBA)',
//   'Supply Chain Management & Logistics (MBA)',
//   'Supply Chain Management and Logistics (MS) ',
//   'Systems Engineering (MS)',
//   'Teaching, Learning and Curriculum (MS)',
//   'Television & Media Management (MS)',
//   'Television & Media Management (MS) / Business Administration (MBA)',
//   'Trial Advocacy and Dispute Resolution (LLM)',
//   'Undergraduate STEM Education (MS)',
//   'Urban Health (MPH)',
//   'Urban Strategy (MS)',
//];
