// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBook = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991),
    author_id: z.number().int().gte(-9007199254740991).lte(9007199254740991),
    title: z.string(),
    pub_year: z.string().max(4),
    genre: z.string()
});

export const zBookCreate = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    author_id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    title: z.string().min(1).max(200),
    pub_year: z.string().max(4).regex(/^\\d{4}$/),
    genre: z.enum([
        'Fiction',
        'Non-Fiction',
        'Mystery',
        'Science Fiction',
        'Fantasy',
        'Romance',
        'Thriller',
        'Horror',
        'Biography',
        'History',
        'Science',
        'Poetry',
        'Drama',
        'Children'
    ]),
    author_name: z.string().min(1).max(100).regex(/^[a-zA-Z\\s\\-\'\\p{L}\\p{M}]+$/),
    author_bio: z.union([
        z.string().max(1000),
        z.null()
    ]).optional()
});

export const zBookUpdate = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    author_id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    title: z.string().min(1).max(200).optional(),
    pub_year: z.string().max(4).regex(/^\\d{4}$/).optional(),
    genre: z.enum([
        'Fiction',
        'Non-Fiction',
        'Mystery',
        'Science Fiction',
        'Fantasy',
        'Romance',
        'Thriller',
        'Horror',
        'Biography',
        'History',
        'Science',
        'Poetry',
        'Drama',
        'Children'
    ]).optional(),
    author_name: z.string().min(1).max(100).regex(/^[a-zA-Z\\s\\-\'\\p{L}\\p{M}]+$/).optional(),
    author_bio: z.union([
        z.string().max(1000),
        z.null()
    ]).optional()
});

export const zAuthor = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991),
    name: z.string(),
    bio: z.union([
        z.string(),
        z.null()
    ])
});

export const zAuthorCreate = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    name: z.string().min(1).max(100).regex(/^[a-zA-Z\\s\\-\'\\p{L}\\p{M}]+$/),
    bio: z.union([
        z.string().max(1000),
        z.null()
    ]).optional()
});

export const zAuthorUpdate = z.object({
    id: z.number().int().gte(-9007199254740991).lte(9007199254740991).optional(),
    name: z.string().min(1).max(100).regex(/^[a-zA-Z\\s\\-\'\\p{L}\\p{M}]+$/).optional(),
    bio: z.union([
        z.string().max(1000),
        z.null()
    ]).optional()
});

export const zGetBooksResponse = z.array(zBook);

export const zPostBooksResponse = zBook;

export const zDeleteBooksByIdResponse = z.void();

export const zGetBooksByIdResponse = zBook;

export const zPutBooksByIdResponse = zBook;

export const zGetAuthorsResponse = z.array(zAuthor);

export const zPostAuthorsResponse = zAuthor;

export const zDeleteAuthorsByIdResponse = z.object({
    deleted_id: z.number()
});

export const zGetAuthorsByIdResponse = zAuthor;

export const zPutAuthorsByIdResponse = zAuthor;
