# Build stage
FROM denoland/deno:latest AS builder
WORKDIR /app
COPY . .
ENV DENO_DIR=/app/.deno_cache
RUN deno compile --no-check -A -o openmario src/server.ts  \
    && chmod +x openmario


FROM denoland/deno:latest
WORKDIR /app
COPY --from=builder /app/openmario /app
