# Build stage
FROM denoland/deno:latest AS builder
WORKDIR /app
COPY . .
RUN deno install
RUN deno task install
RUN deno cache src/server.ts

FROM denoland/deno:latest
WORKDIR /app
COPY --from=builder /app .
