/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalaryDialogRouteImport } from './routes/salary/_dialog'
import { Route as SalaryDialogReportRouteImport } from './routes/salary/_dialog.report'
import { Route as SalaryDialogDraftsRouteImport } from './routes/salary/_dialog.drafts'
import { Route as SalaryDialogAutoFillRouteImport } from './routes/salary/_dialog.auto-fill'

const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryDialogRoute = SalaryDialogRouteImport.update({
  id: '/_dialog',
  getParentRoute: () => SalaryRoute,
} as any)
const SalaryDialogReportRoute = SalaryDialogReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogDraftsRoute = SalaryDialogDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SalaryDialogRoute,
} as any)
const SalaryDialogAutoFillRoute = SalaryDialogAutoFillRouteImport.update({
  id: '/auto-fill',
  path: '/auto-fill',
  getParentRoute: () => SalaryDialogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/salary': typeof SalaryDialogRouteWithChildren
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/report': typeof SalaryDialogReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salary': typeof SalaryDialogRouteWithChildren
  '/salary/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/drafts': typeof SalaryDialogDraftsRoute
  '/salary/report': typeof SalaryDialogReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/salary': typeof SalaryRouteWithChildren
  '/salary/_dialog': typeof SalaryDialogRouteWithChildren
  '/salary/_dialog/auto-fill': typeof SalaryDialogAutoFillRoute
  '/salary/_dialog/drafts': typeof SalaryDialogDraftsRoute
  '/salary/_dialog/report': typeof SalaryDialogReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/salary'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/salary'
    | '/salary/auto-fill'
    | '/salary/drafts'
    | '/salary/report'
  id:
    | '__root__'
    | '/'
    | '/salary'
    | '/salary/_dialog'
    | '/salary/_dialog/auto-fill'
    | '/salary/_dialog/drafts'
    | '/salary/_dialog/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalaryRoute: typeof SalaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary/_dialog': {
      id: '/salary/_dialog'
      path: ''
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryDialogRouteImport
      parentRoute: typeof SalaryRoute
    }
    '/salary/_dialog/report': {
      id: '/salary/_dialog/report'
      path: '/report'
      fullPath: '/salary/report'
      preLoaderRoute: typeof SalaryDialogReportRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/drafts': {
      id: '/salary/_dialog/drafts'
      path: '/drafts'
      fullPath: '/salary/drafts'
      preLoaderRoute: typeof SalaryDialogDraftsRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
    '/salary/_dialog/auto-fill': {
      id: '/salary/_dialog/auto-fill'
      path: '/auto-fill'
      fullPath: '/salary/auto-fill'
      preLoaderRoute: typeof SalaryDialogAutoFillRouteImport
      parentRoute: typeof SalaryDialogRoute
    }
  }
}

interface SalaryDialogRouteChildren {
  SalaryDialogAutoFillRoute: typeof SalaryDialogAutoFillRoute
  SalaryDialogDraftsRoute: typeof SalaryDialogDraftsRoute
  SalaryDialogReportRoute: typeof SalaryDialogReportRoute
}

const SalaryDialogRouteChildren: SalaryDialogRouteChildren = {
  SalaryDialogAutoFillRoute: SalaryDialogAutoFillRoute,
  SalaryDialogDraftsRoute: SalaryDialogDraftsRoute,
  SalaryDialogReportRoute: SalaryDialogReportRoute,
}

const SalaryDialogRouteWithChildren = SalaryDialogRoute._addFileChildren(
  SalaryDialogRouteChildren,
)

interface SalaryRouteChildren {
  SalaryDialogRoute: typeof SalaryDialogRouteWithChildren
}

const SalaryRouteChildren: SalaryRouteChildren = {
  SalaryDialogRoute: SalaryDialogRouteWithChildren,
}

const SalaryRouteWithChildren =
  SalaryRoute._addFileChildren(SalaryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalaryRoute: SalaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
