export const Minors = [
   'Accounting',
   'Actuarial Science',
   'Africana Studies',
   'Animation and Visual Effects',
   'Architectural Engineering',
   'Architecture',
   'Art History',
   'Artificial Intelligence and Learning',
   'Asian Studies',
   'Astrophysics',
   'Behavioral Economics and Business',
   'Biochemistry',
   'Bioinformatics',
   'Biological Sciences',
   'Biophysics',
   'Bioscience and Society',
   'Business Administration',
   'Business Analytics',
   'Business Consulting',
   'Business Law',
   'Chemical Engineering',
   'Chemistry',
   'Client Development and Customer Service',
   'Climate Change',
   'Communication',
   'Computer Engineering',
   'Computer Science',
   'Computing Technology',
   'Construction Management',
   'Corporate Entrepreneurship',
   'Crime Analysis and Digital Investigations',
   'Criminal Justice',
   'Culinary Arts',
   'Dance',
   'Data Science',
   'DragonsTeach Certification Minor',
   'DragonsTeach Middle Years Minor',
   'DragonsTeach Middle Years Certification Minor',
   'Ecology',
   'Economics',
   'Econometrics and Data Analytics',
   'Education',
   'Electrical Engineering',
   'Engineering Leadership',
   'Engineering Management',
   'Engineering Policy Analysis',
   'English',
   'Entertainment & Arts Management',
   'Entrepreneurship and Innovation',
   'Environmental Engineering',
   'Environmental Public Health',
   'Environmental Sociology',
   'Environmental Studies',
   'Epidemiology',
   'Esports',
   'European Studies',
   'Exercise Science',
   'Film & Television Production',
   'Film & Television Studies',
   'Film Studies',
   'Finance',
   'Financial Technology',
   'Fine Arts',
   'Food Science',
   'Food Studies',
   'French',
   'Game Design and Production',
   'Gender and Sexuality Studies',
   'Geoscience',
   'Global Engineering',
   'Global Public Health',
   'Global Studies',
   'Graphic Design',
   'Green Energy and Sustainability',
   'Health and Social Justice',
   'Health Data Analytics',
   'Health Services Administration',
   'History',
   'History of Capitalism',
   'Hospitality Management',
   'Human Computer Interaction',
   'Immune Engineering',
   'Information Systems',
   'Interdisciplinary Problem Solving',
   'International Business',
   'Japanese',
   'Jazz and African-American Music',
   'Jewish Studies',
   'Justice Studies',
   'Law',
   'Linguistics',
   'Management Information Systems',
   'Marketing',
   'Materials Science and Engineering',
   'Mathematics',
   'Mechanical Engineering and Mechanics',
   'Medical Sociology',
   'Merchandising',
   'Middle East and North Africa Studies',
   'Military Science',
   'Music',
   'Music Performance',
   'Music Theory and Composition',
   'Neuroscience',
   'Nonprofit Communication',
   'Nutrition',
   'Operations and Supply Chain Management',
   'Organizational Management',
   'Performing Arts',
   'Philosophy',
   'Photography',
   'Physics',
   'Playwriting',
   'Poetry, Biblio and Expressive Writing Facilitation',
   'Politics',
   'Product Design',
   'Project Management',
   'Psychiatric Rehabilitation',
   'Psychology',
   'Public Health',
   'Real Estate Management and Development',
   'Religious Studies',
   'Robotics and Automation',
   'Science, Technology and Society',
   'Screenwriting',
   'Security Technology',
   'Social Entrepreneurship',
   'Sociology',
   'Software Engineering',
   'Somatics',
   'Spanish',
   'Sport Coaching Leadership',
   'Sport Management',
   'Sport Regulation & Compliance',
   'STEM Education',
   'Sustainability in the Built Environment',
   'Systems Engineering',
   'Technology Innovation Management',
   'Theatre',
   'User Experience and Interaction Design',
   'Virtual Reality & Immersive Media',
   'War and Society',
   'Writing',
] as const;

export const Majors = [
   'Accounting (BSBA)',
   'Air Force ROTC',
   'Animation & Visual Effects (BS)',
   'Architectural Engineering (BSAE)',
   'Architectural Studies (BS)',
   'Architecture (BArch)',
   'Army ROTC',
   'Art History (BA)',
   'Art History (BS)',
   'Behavioral Economics, Business and Organizations (BS)',
   'Biological Sciences (BS)',
   'Biomedical Engineering (BS)',
   'Business (General) (BSBA)',
   'Business Undeclared',
   'Business and Engineering (BSBAE)',
   'Business Analytics (BSBA)',
   'Business Administration (BSBA)',
   'Business Law (BSBA)',
   'Chemical Engineering (BSCHE)',
   'Chemistry (BA)',
   'Chemistry (BS)',
   'Chemistry-Biochemistry Concentration (BS)',
   'Civil Engineering (BSCIV)',
   'Communication (BA)',
   'Computer Engineering (BSCE)',
   'Computer Science (BACS)',
   'Computer Science (BSCS)',
   'Computing and Security Technology (BSCST)',
   'Construction Management (BSCMGT)',
   'Criminology and Justice Studies (BS)',
   'Culinary Arts & Science (BSCAS)',
   'Custom-Designed Major (BS)',
   'Dance (BS)',
   'Dance - Part-time Professional (BS)',
   'Data Science (BS)',
   'Digital Media and Virtual Production (BS)',
   'Economic Analysis (BAECON)',
   'Economics (BSECON)',
   'Economics and Business (BS)',
   'Economics and Data Science (BSECDS)',
   'Economics and Mathematics (BS)',
   'Economics and Public Health (BS)',
   'Educational Studies & Innovation (BS)',
   'Education: Non-Certification (BS)',
   'Electrical Engineering (BSEE)',
   'Elementary Education (BS)',
   'Engineering (BSE)',
   'Engineering Technology (BSET)',
   'Engineering Undeclared',
   'English, Literary Studies Concentration (BA)',
   'English, Writing Concentration (BA)',
   'English, Secondary Education Concentration (BA)',
   'Entertainment and Arts Management (BS)',
   'Entrepreneurship and Innovation (BA)',
   'Entrepreneurship & Innovation 3-year Option (BA)',
   'Environmental Engineering (BSENE)',
   'Environmental Science (BS)',
   'Environmental Studies and Sustainability (BA)',
   'Esport Business (BSBA)',
   'Exercise Science (BS)',
   'Fashion Design (BS)',
   'Fashion Industry & Merchandising (BS)',
   'Film & Television (BS)',
   'Finance (BSBA)',
   'First Year Exploratory Studies (Non-degree)',
   'Game Design & Production (BS)',
   'General Business (BSBA)',
   'General Humanities and Social Sciences (Undeclared)',
   'Global Public Health (BA)',
   'Global Studies (BA) ',
   'Graphic Design (BS)',
   'Health Data Analytics (BS)',
   'Health Sciences (BS)',
   'Health Services Administration (BS)',
   'History (BA)',
   'Hospitality Management (BSHM)',
   'Human Development and Counseling (BS)',
   'Information Systems (BS)',
   'Interdisciplinary Professional Studies (BS)',
   'International Business (BSBA)',
   'Interior Design (BS)',
   'Law (BA)',
   'Learning Sciences, Experience Design, and Technology',
   'Management Information Systems (BSBA)',
   'Marketing (BSBA)',
   'Materials Science and Engineering (BSMSE)',
   'Mathematical Statistics (BS)',
   'Mathematics (BA)',
   'Mathematics (BS)',
   'Mechanical Engineering & Mechanics (BSME)',
   'Music Industry (BS)',
   'Navy ROTC',
   'Neuroscience (BS)',
   'Nursing (BSN)',
   'Nursing: RN-MSN Bridge Program',
   'Nutrition and Foods (BS)',
   'Operations and Supply Chain Management (BSBA)',
   'Organizational Management (co-major) (BSBA)',
   'Philosophy (BA)',
   'Philosophy, Politics and Economics (BA)',
   'Photography (BS)',
   'Physics (BS)',
   'Political Science (BA)',
   'Product Design (BS)',
   'Psychology (BS)',
   'Public Health (BS)',
   'Real Estate Management and Development (BSBA)',
   'ROTC (Air Force, Army, Navy)',
   'Science (Undeclared)',
   'Screenwriting and Playwriting (BS)',
   'Sociology (BA)',
   'Software Engineering (BS)',
   'Special Education (PK-12) (BS)',
   'Sport Business (BSBA)',
   'Sustainability and Innovation (BS)',
   'Teacher Education (BS)',
   'Technology Innovation Management (co-major) (BS)',
   'User Experience and Interaction Design (BS)',
   'Westphal Studies Program (BS)',
] as const;
