DROP MATERIALIZED VIEW "public"."submission_m_view";--> statement-breakpoint
DROP MATERIALIZED VIEW "public"."instructor_profile_m_view";--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."submissions_m_view" WITH (fillfactor = 90) AS (select "submission"."id", "submission"."year", "submission"."coop_year", "submission"."coop_cycle", "submission"."program_level", "submission"."work_hours", "submission"."compensation", "submission"."other_compensation", "submission"."details", "submission"."owner_id", "submission"."created_at", "company"."id" as "company_id", "position"."id" as "position_id", "company"."name" as "company_name", "position"."name" as "position_name", "location"."city" as "city", "location"."state" as "state", "location"."state_code" as "state_code", 
          coalesce("company"."name", '')                  || ' ' ||
          coalesce("position"."name", '')                 || ' ' ||
          coalesce("location"."city", '')                 || ' ' ||
          coalesce("location"."state", '')                || ' ' ||
          coalesce("location"."state_code", '')           || ' ' ||
          coalesce("submission"."details", '')            || ' ' ||
          coalesce("submission"."other_compensation", '')
         as "search_text" from "submission" left join "position" on "submission"."position_id" = "position"."id" left join "location" on "submission"."location_id" = "location"."id" left join "company" on "position"."company_id" = "company"."id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."instructor_profile_m_view" AS (select "instructor"."id" as "instructor_id", "instructor"."name" as "instructor_name", "instructor"."department", "instructor"."avg_rating", "instructor"."avg_difficulty", "instructor"."num_ratings", "instructor"."rmp_id", "instructor"."rmp_legacy_id", count(distinct "section"."crn") as "total_sections_taught", count(distinct "course"."id") as "total_courses_taught", count(distinct "section"."term_id") as "total_terms_active", max("section"."term_id") as "most_recent_term", array_agg(distinct "subject"."id") as "subjects_taught", array_agg(distinct "section"."instruction_method") as "instruction_methods" from "instructor" left join "instructor_sections" on "instructor_sections"."instructor_id" = "instructor"."id" left join "section" on "section"."crn" = "instructor_sections"."section_crn" left join "course" on "course"."id" = "section"."course_id" left join "subject" on "subject"."id" = "section"."subject_code" group by "instructor"."id", "instructor"."name", "instructor"."department", "instructor"."avg_rating", "instructor"."avg_difficulty", "instructor"."num_ratings", "instructor"."rmp_id", "instructor"."rmp_legacy_id");