// This file is auto-generated by @hey-api/openapi-ts

/**
 * Complete author record with all properties
 */
export type Author = {
    id: number;
    name: string;
    bio: (string) | null;
};

/**
 * Schema for creating a new author record
 */
export type AuthorCreate = {
    id?: number;
    /**
     * Author's full name
     */
    name: string;
    /**
     * Author's biographical information
     */
    bio?: (string) | null;
};

/**
 * Schema for updating an existing author record
 */
export type AuthorUpdate = {
    id?: number;
    /**
     * Author's full name
     */
    name?: string;
    /**
     * Author's biographical information
     */
    bio?: (string) | null;
};

/**
 * A book record with all its properties
 */
export type Book = {
    id: number;
    author_id: number;
    title: string;
    pub_year: string;
    genre: string;
};

/**
 * Schema for creating a new book record
 */
export type BookCreate = {
    id?: number;
    author_id?: number;
    /**
     * The title of the book
     */
    title: string;
    /**
     * The year the book was published
     */
    pub_year: string;
    /**
     * The genre of the book
     */
    genre: 'Fiction' | 'Non-Fiction' | 'Mystery' | 'Science Fiction' | 'Fantasy' | 'Romance' | 'Thriller' | 'Horror' | 'Biography' | 'History' | 'Science' | 'Poetry' | 'Drama' | 'Children';
    /**
     * The name of the book's author
     */
    author_name: string;
    /**
     * Optional biography of the author
     */
    author_bio?: (string) | null;
};

/**
 * The genre of the book
 */
export type genre = 'Fiction' | 'Non-Fiction' | 'Mystery' | 'Science Fiction' | 'Fantasy' | 'Romance' | 'Thriller' | 'Horror' | 'Biography' | 'History' | 'Science' | 'Poetry' | 'Drama' | 'Children';

/**
 * Schema for updating an existing book record
 */
export type BookUpdate = {
    id?: number;
    author_id?: number;
    /**
     * The title of the book
     */
    title?: string;
    /**
     * The year the book was published
     */
    pub_year?: string;
    /**
     * The genre of the book
     */
    genre?: 'Fiction' | 'Non-Fiction' | 'Mystery' | 'Science Fiction' | 'Fantasy' | 'Romance' | 'Thriller' | 'Horror' | 'Biography' | 'History' | 'Science' | 'Poetry' | 'Drama' | 'Children';
    /**
     * The updated name of the book's author
     */
    author_name?: string;
    /**
     * Updated biography of the author
     */
    author_bio?: (string) | null;
};

export type GetAuthorsData = {
    bio?: string;
    name?: string;
};

export type GetAuthorsResponse = (Array<Author>);

export type PostAuthorsData = {
    requestBody?: AuthorCreate;
};

export type PostAuthorsResponse = (Author);

export type GetAuthorsByIdData = {
    id: number;
};

export type GetAuthorsByIdResponse = (Author);

export type PutAuthorsByIdData = {
    id: number;
    requestBody?: AuthorUpdate;
};

export type PutAuthorsByIdResponse = (Author);

export type DeleteAuthorsByIdData = {
    id: number;
};

export type DeleteAuthorsByIdResponse = ({
    deleted_id: number;
});

export type GetBooksData = {
    genre?: 'Fiction' | 'Non-Fiction' | 'Mystery' | 'Science Fiction' | 'Fantasy' | 'Romance' | 'Thriller' | 'Horror' | 'Biography' | 'History' | 'Science' | 'Poetry' | 'Drama' | 'Children';
    pubYear?: string;
    title?: string;
};

export type GetBooksResponse = (Array<Book>);

export type PostBooksData = {
    requestBody?: BookCreate;
};

export type PostBooksResponse = (Book);

export type GetBooksByIdData = {
    id: number;
};

export type GetBooksByIdResponse = (Book);

export type PutBooksByIdData = {
    id: number;
    requestBody?: BookUpdate;
};

export type PutBooksByIdResponse = (Book);

export type DeleteBooksByIdData = {
    id: number;
};

export type DeleteBooksByIdResponse = (void);
