// This file is auto-generated by @hey-api/openapi-ts

export const BookSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        author_id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        title: {
            type: 'string'
        },
        pub_year: {
            type: 'string',
            maxLength: 4
        },
        genre: {
            type: 'string'
        }
    },
    required: ['id', 'author_id', 'title', 'pub_year', 'genre']
} as const;

export const BookCreateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        author_id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        title: {
            type: 'string',
            minLength: 1,
            maxLength: 200,
            example: 'The Great Gatsby'
        },
        pub_year: {
            type: 'string',
            maxLength: 4,
            pattern: '^\\d{4}$',
            example: '2023'
        },
        genre: {
            type: 'string',
            minLength: 1,
            example: 'Fiction',
            enum: ['Fiction', 'Non-Fiction', 'Mystery', 'Science Fiction', 'Fantasy', 'Romance', 'Thriller', 'Horror', 'Biography', 'History', 'Science', 'Poetry', 'Drama', 'Children']
        },
        author_name: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
            pattern: "^[a-zA-Z\\s\\-'\\p{L}\\p{M}]+$",
            example: 'John Doe'
        },
        author_bio: {
            type: 'string',
            nullable: true,
            maxLength: 1000,
            example: 'An accomplished writer with multiple bestsellers'
        }
    },
    required: ['title', 'pub_year', 'genre', 'author_name'],
    additionalProperties: false
} as const;

export const BookUpdateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        author_id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        title: {
            type: 'string',
            minLength: 1,
            maxLength: 200,
            example: 'The Great Gatsby'
        },
        pub_year: {
            type: 'string',
            maxLength: 4,
            pattern: '^\\d{4}$',
            example: '2023'
        },
        genre: {
            type: 'string',
            minLength: 1,
            example: 'Fiction',
            enum: ['Fiction', 'Non-Fiction', 'Mystery', 'Science Fiction', 'Fantasy', 'Romance', 'Thriller', 'Horror', 'Biography', 'History', 'Science', 'Poetry', 'Drama', 'Children']
        },
        author_name: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
            pattern: "^[a-zA-Z\\s\\-'\\p{L}\\p{M}]+$",
            example: 'Jane Smith'
        },
        author_bio: {
            type: 'string',
            nullable: true,
            maxLength: 1000,
            example: 'Award-winning author of contemporary fiction'
        }
    },
    additionalProperties: false
} as const;

export const AuthorSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        name: {
            type: 'string'
        },
        bio: {
            type: 'string',
            nullable: true
        }
    },
    required: ['id', 'name', 'bio']
} as const;

export const AuthorCreateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
            pattern: "^[a-zA-Z\\s\\-'\\p{L}\\p{M}]+$",
            example: 'Jane Austen'
        },
        bio: {
            type: 'string',
            nullable: true,
            maxLength: 1000,
            example: 'A renowned author known for her works in classic literature'
        }
    },
    required: ['name'],
    additionalProperties: false
} as const;

export const AuthorUpdateSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991
        },
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
            pattern: "^[a-zA-Z\\s\\-'\\p{L}\\p{M}]+$",
            example: 'Jane Austen'
        },
        bio: {
            type: 'string',
            nullable: true,
            maxLength: 1000,
            example: 'A renowned author known for her works in classic literature'
        }
    },
    additionalProperties: false
} as const;
