// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { PostAuthSignupData, PostAuthSignupResponse, PostAuthMeData, PostAuthMeResponse, PostAuthLogoutData, PostAuthAccessTokenData, PostAuthAccessTokenResponse, GetBooksData, GetBooksResponse, PostBooksData, PostBooksResponse, DeleteBooksByIdData, DeleteBooksByIdResponse, GetBooksByIdData, GetBooksByIdResponse, PutBooksByIdData, PutBooksByIdResponse, GetAuthorsData, GetAuthorsResponse, PostAuthorsData, PostAuthorsResponse, DeleteAuthorsByIdData, DeleteAuthorsByIdResponse, GetAuthorsByIdData, GetAuthorsByIdResponse, PutAuthorsByIdData, PutAuthorsByIdResponse } from './types.gen';

export const client = createClient(createConfig({
    auth: () => localStorage.getItem('access_token') || '',
    baseURL: "/api",
}));


export class AuthenticationService {
    /**
     * Register a new user
     */
    public static postAuthSignup<ThrowOnError extends boolean = false>(options?: Options<PostAuthSignupData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthSignupResponse, unknown, ThrowOnError>({
            url: '/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    /**
     * Logout user and invalidate tokens
     */
    public static postAuthMe<ThrowOnError extends boolean = false>(options?: Options<PostAuthMeData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthMeResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/me',
            ...options
        });
    }

    /**
     * Logout user and invalidate tokens
     */
    public static postAuthLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/logout',
            ...options
        });
    }

    /**
     * Authorize user credentials
     */
    public static postAuthAccessToken<ThrowOnError extends boolean = false>(options?: Options<PostAuthAccessTokenData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthAccessTokenResponse, unknown, ThrowOnError>({
            url: '/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

}

export class BooksService {
    /**
     * Get all books with optional filtering
     */
    public static getBooks<ThrowOnError extends boolean = false>(options?: Options<GetBooksData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBooksResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/books',
            ...options
        });
    }

    /**
     * Create a new book
     */
    public static postBooks<ThrowOnError extends boolean = false>(options?: Options<PostBooksData, ThrowOnError>) {
        return (options?.client ?? client).post<PostBooksResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/books',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    /**
     * Delete a book
     */
    public static deleteBooksById<ThrowOnError extends boolean = false>(options: Options<DeleteBooksByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteBooksByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/books/{id}',
            ...options
        });
    }

    /**
     * Get a book by its ID
     */
    public static getBooksById<ThrowOnError extends boolean = false>(options: Options<GetBooksByIdData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBooksByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/books/{id}',
            ...options
        });
    }

    /**
     * Update an existing book
     */
    public static putBooksById<ThrowOnError extends boolean = false>(options: Options<PutBooksByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutBooksByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/books/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

}

export class AuthorsService {
    /**
     * Get all authors
     */
    public static getAuthors<ThrowOnError extends boolean = false>(options?: Options<GetAuthorsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAuthorsResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/authors',
            ...options
        });
    }

    /**
     * Create an author
     */
    public static postAuthors<ThrowOnError extends boolean = false>(options?: Options<PostAuthorsData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthorsResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/authors',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    /**
     * Delete an author
     */
    public static deleteAuthorsById<ThrowOnError extends boolean = false>(options: Options<DeleteAuthorsByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteAuthorsByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/authors/{id}',
            ...options
        });
    }

    /**
     * Get author by id
     */
    public static getAuthorsById<ThrowOnError extends boolean = false>(options: Options<GetAuthorsByIdData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAuthorsByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/authors/{id}',
            ...options
        });
    }

    /**
     * Update an author
     */
    public static putAuthorsById<ThrowOnError extends boolean = false>(options: Options<PutAuthorsByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutAuthorsByIdResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/authors/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

}
