// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-axios";
import type {
  PostAuthLoginData,
  PostAuthLoginResponse,
  PostAuthLoginError,
  GetAuthLoginTokenData,
  GetAuthLoginTokenResponse,
  GetAuthLoginTokenError,
  GetAutocompleteCompanyData,
  GetAutocompleteCompanyResponse,
  GetAutocompleteCompanyError,
  GetAutocompletePositionData,
  GetAutocompletePositionResponse,
  GetAutocompletePositionError,
  GetAutocompleteLocationData,
  GetAutocompleteLocationResponse,
  GetAutocompleteLocationError,
  GetCompanyPositionData,
  GetCompanyPositionResponse,
  GetCompanyPositionError,
  PostCompanyPositionData,
  PostCompanyPositionResponse,
  PostCompanyPositionError,
  PatchCompanyData,
  PatchCompanyResponse,
  PatchCompanyError,
  PatchPositionData,
  PatchPositionResponse,
  PatchPositionError,
  GetSubmissionsData,
  GetSubmissionsResponse,
  GetSubmissionsError,
  PatchSubmissionsData,
  PatchSubmissionsResponse,
  PatchSubmissionsError,
  PostSubmissionsData,
  PostSubmissionsResponse,
  PostSubmissionsError,
  GetSubmissionsMeData,
  GetSubmissionsMeResponse,
  GetSubmissionsMeError,
} from "./types.gen";

export const client = createClient(
  createConfig({
    auth: () => localStorage.getItem("access_token") || "",
    baseURL: "/api/v1",
  }),
);

export class AuthService {
  /**
   * Request a magic link for authentication
   */
  public static postAuthLogin<ThrowOnError extends boolean = false>(
    options: Options<PostAuthLoginData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostAuthLoginResponse,
      PostAuthLoginError,
      ThrowOnError
    >({
      url: "/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Verify magic link token and authenticate user
   */
  public static getAuthLoginToken<ThrowOnError extends boolean = false>(
    options: Options<GetAuthLoginTokenData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetAuthLoginTokenResponse,
      GetAuthLoginTokenError,
      ThrowOnError
    >({
      url: "/auth/login/:token",
      ...options,
    });
  }
}

export class SearchService {
  /**
   * Search for companies by name with fuzzy matching
   */
  public static getAutocompleteCompany<ThrowOnError extends boolean = false>(
    options: Options<GetAutocompleteCompanyData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetAutocompleteCompanyResponse,
      GetAutocompleteCompanyError,
      ThrowOnError
    >({
      url: "/autocomplete/company",
      ...options,
    });
  }

  /**
   * Search for positions within a specific company
   */
  public static getAutocompletePosition<ThrowOnError extends boolean = false>(
    options: Options<GetAutocompletePositionData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetAutocompletePositionResponse,
      GetAutocompletePositionError,
      ThrowOnError
    >({
      url: "/autocomplete/position",
      ...options,
    });
  }

  /**
   * Search for locations with fuzzy matching across city, state, and state code
   */
  public static getAutocompleteLocation<ThrowOnError extends boolean = false>(
    options: Options<GetAutocompleteLocationData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetAutocompleteLocationResponse,
      GetAutocompleteLocationError,
      ThrowOnError
    >({
      url: "/autocomplete/location",
      ...options,
    });
  }
}

export class CompaniesAndPositionsService {
  /**
   * Retrieve companies and positions owned by the authenticated user
   */
  public static getCompanyPosition<ThrowOnError extends boolean = false>(
    options?: Options<GetCompanyPositionData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetCompanyPositionResponse,
      GetCompanyPositionError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/company-position",
      ...options,
    });
  }

  /**
   * Create a new company and position pair
   */
  public static postCompanyPosition<ThrowOnError extends boolean = false>(
    options: Options<PostCompanyPositionData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostCompanyPositionResponse,
      PostCompanyPositionError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/company-position",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Update an existing company name
   */
  public static patchCompany<ThrowOnError extends boolean = false>(
    options: Options<PatchCompanyData, ThrowOnError>,
  ) {
    return (options?.client ?? client).patch<
      PatchCompanyResponse,
      PatchCompanyError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/company",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Update an existing position name
   */
  public static patchPosition<ThrowOnError extends boolean = false>(
    options: Options<PatchPositionData, ThrowOnError>,
  ) {
    return (options?.client ?? client).patch<
      PatchPositionResponse,
      PatchPositionError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/position",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class SubmissionsService {
  /**
   * Retrieve co-op submission records with pagination and filtering
   */
  public static getSubmissions<ThrowOnError extends boolean = false>(
    options?: Options<GetSubmissionsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetSubmissionsResponse,
      GetSubmissionsError,
      ThrowOnError
    >({
      url: "/submissions",
      ...options,
    });
  }

  /**
   * Update an existing co-op submission
   */
  public static patchSubmissions<ThrowOnError extends boolean = false>(
    options: Options<PatchSubmissionsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).patch<
      PatchSubmissionsResponse,
      PatchSubmissionsError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/submissions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Create new co-op submission(s)
   */
  public static postSubmissions<ThrowOnError extends boolean = false>(
    options: Options<PostSubmissionsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostSubmissionsResponse,
      PostSubmissionsError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/submissions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Retrieve all co-op submissions owned by the authenticated user
   */
  public static getSubmissionsMe<ThrowOnError extends boolean = false>(
    options?: Options<GetSubmissionsMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetSubmissionsMeResponse,
      GetSubmissionsMeError,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/submissions/me",
      ...options,
    });
  }
}
